// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Bucket is the Schema for the buckets API
 */
export class Bucket extends pulumi.CustomResource {
    /**
     * Get an existing Bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bucket {
        return new Bucket(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:source.toolkit.fluxcd.io/v1beta1:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"source.toolkit.fluxcd.io/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"Bucket" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * BucketSpec defines the desired state of an S3 compatible bucket
     */
    public readonly spec!: pulumi.Output<outputs.source.v1beta1.BucketSpec | undefined>;
    /**
     * BucketStatus defines the observed state of a bucket
     */
    public readonly status!: pulumi.Output<outputs.source.v1beta1.BucketStatus | undefined>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BucketArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "source.toolkit.fluxcd.io/v1beta1";
            resourceInputs["kind"] = "Bucket";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.source.v1beta1.bucketSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    apiVersion?: pulumi.Input<"source.toolkit.fluxcd.io/v1beta1">;
    kind?: pulumi.Input<"Bucket">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * BucketSpec defines the desired state of an S3 compatible bucket
     */
    spec?: pulumi.Input<inputs.source.v1beta1.BucketSpecArgs>;
    /**
     * BucketStatus defines the observed state of a bucket
     */
    status?: pulumi.Input<inputs.source.v1beta1.BucketStatusArgs>;
}
