apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"helm.toolkit.fluxcd.io/v2beta1","kind":"HelmRelease","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"connect","namespace":"1password"},"spec":{"chart":{"spec":{"chart":"connect","reconcileStrategy":"ChartVersion","sourceRef":{"kind":"HelmRepository","name":"1password","namespace":"flux-system"},"version":"*"}},"interval":"24h","values":{"operator":{"create":true}}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: connect
  namespace: 1password
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    operator:
      create: true
