apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.9.2
    helm.sh/chart: promtail-6.15.3
  name: loki-stack-promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: loki-stack
      app.kubernetes.io/name: promtail
  template:
    metadata:
      annotations:
        checksum/config: 909a134a4a2c50e7ca0fb7337915817e69246ea8fa8b0564e0ef166a0b558864
      labels:
        app.kubernetes.io/instance: loki-stack
        app.kubernetes.io/name: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/promtail.yaml
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: docker.io/grafana/promtail:2.9.2
          imagePullPolicy: IfNotPresent
          name: promtail
          ports:
            - containerPort: 3101
              name: http-metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/promtail
              name: config
            - mountPath: /run/promtail
              name: run
            - mountPath: /var/lib/docker/containers
              name: containers
              readOnly: true
            - mountPath: /var/log/pods
              name: pods
              readOnly: true
      enableServiceLinks: true
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: loki-stack-promtail
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: config
          secret:
            secretName: loki-stack-promtail
        - hostPath:
            path: /run/promtail
          name: run
        - hostPath:
            path: /var/lib/docker/containers
          name: containers
        - hostPath:
            path: /var/log/pods
          name: pods
  updateStrategy: {}
