apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: loki
    chart: loki-2.16.0
    heritage: Helm
    release: loki-stack
  name: loki-stack
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-stack
subjects:
  - kind: ServiceAccount
    name: loki-stack
