apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: loki
    chart: loki-2.16.0
    heritage: Helm
    release: loki-stack
  name: loki-stack
  namespace: monitoring
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - loki-stack
    resources:
      - podsecuritypolicies
    verbs:
      - use
