apiVersion: v1
kind: Secret
metadata:
  labels:
    app: kube-prometheus-stack-prometheus-scrape-confg
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 55.8.1
    chart: kube-prometheus-stack-55.8.1
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-prometheus-scrape-confg
  namespace: monitoring
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogT3BlbldydAogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czoKICAgIC0gMTkyLjE2OC4wLjE6OTEwMA==
