apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: misc
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: misc-memos-c8cf5c27
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: misc-memos-c8cf5c27
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: MEMOS_MODE
              value: prod
            - name: MEMOS_ADDR
              value: 0.0.0.0
            - name: MEMOS_PORT
              value: "5320"
            - name: MEMOS_DATA
              value: /var/opt/memos
            - name: MEMOS_DRIVER
              value: sqlite
          image: neosmemo/memos:stable
          imagePullPolicy: Always
          name: memos
          ports:
            - containerPort: 5230
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5230
          volumeMounts:
            - mountPath: /var/opt/memos
              name: memos
      dnsPolicy: Default
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /zssd/general/memos
            type: ""
          name: memos
