apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: misc
spec:
  externalIPs: []
  ports:
    - port: 5230
      targetPort: 5230
  selector:
    cdk8s.io/metadata.addr: misc-memos-c8cf5c27
  type: ClusterIP
