apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
- "bazarr.yaml"
- "namespace.yaml"
- "plex.yaml"
- "prowlarr.yaml"
- "qbittorrent.yaml"
- "radarr.yaml"
- "readarr.yaml"
- "sonarr.yaml"