// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { OnePasswordItemArgs } from "./onePasswordItem";
export type OnePasswordItem = import("./onePasswordItem").OnePasswordItem;
export const OnePasswordItem: typeof import("./onePasswordItem").OnePasswordItem = null as any;
utilities.lazyLoad(exports, ["OnePasswordItem"], () => require("./onePasswordItem"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:onepassword.com/v1:OnePasswordItem":
                return new OnePasswordItem(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("onepassword", "onepassword.com/v1", _module)
