// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * OnePasswordItem is the Schema for the onepassworditems API
 */
export class OnePasswordItem extends pulumi.CustomResource {
    /**
     * Get an existing OnePasswordItem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OnePasswordItem {
        return new OnePasswordItem(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:onepassword.com/v1:OnePasswordItem';

    /**
     * Returns true if the given object is an instance of OnePasswordItem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OnePasswordItem {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OnePasswordItem.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"onepassword.com/v1" | undefined>;
    public readonly kind!: pulumi.Output<"OnePasswordItem" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * OnePasswordItemSpec defines the desired state of OnePasswordItem
     */
    public readonly spec!: pulumi.Output<outputs.onepassword.v1.OnePasswordItemSpec | undefined>;
    /**
     * OnePasswordItemStatus defines the observed state of OnePasswordItem
     */
    public readonly status!: pulumi.Output<outputs.onepassword.v1.OnePasswordItemStatus | undefined>;
    /**
     * Kubernetes secret type. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
     */
    public readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a OnePasswordItem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OnePasswordItemArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "onepassword.com/v1";
            resourceInputs["kind"] = "OnePasswordItem";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OnePasswordItem.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a OnePasswordItem resource.
 */
export interface OnePasswordItemArgs {
    apiVersion?: pulumi.Input<"onepassword.com/v1">;
    kind?: pulumi.Input<"OnePasswordItem">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * OnePasswordItemSpec defines the desired state of OnePasswordItem
     */
    spec?: pulumi.Input<inputs.onepassword.v1.OnePasswordItemSpecArgs>;
    /**
     * OnePasswordItemStatus defines the observed state of OnePasswordItem
     */
    status?: pulumi.Input<inputs.onepassword.v1.OnePasswordItemStatusArgs>;
    /**
     * Kubernetes secret type. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
     */
    type?: pulumi.Input<string>;
}
