apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"helm.toolkit.fluxcd.io/v2beta1","kind":"HelmRelease","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"plex","namespace":"media"},"spec":{"chart":{"spec":{"chart":"plex","reconcileStrategy":"ChartVersion","sourceRef":{"kind":"HelmRepository","name":"geek-cookbook","namespace":"flux-system"},"version":"*"}},"interval":"24h","values":{"env":{"PGID":100,"PUID":1000,"TZ":"America/Los_Angeles"},"hostNetwork":true,"image":{"imagePullPolicy":"Always","repository":"ghcr.io/linuxserver/plex","tag":"latest"},"ingress":{"main":{"enabled":false}},"persistence":{"audiobooks":{"enabled":true,"hostPath":"/data/media/audiobooks","mountPath":"/audiobooks","type":"hostPath"},"config":{"enabled":true,"hostPath":"/data/general/config/plex","mountPath":"/config","type":"hostPath"},"movies":{"enabled":true,"hostPath":"/data/media/movies","mountPath":"/movies","type":"hostPath"},"transcode":{"enabled":true,"medium":"Memory","type":"emptyDir"},"tv":{"enabled":true,"hostPath":"/data/media/tv","mountPath":"/tv","type":"hostPath"}},"podAnnotations":{"container.apparmor.security.beta.kubernetes.io/plex":"unconfined"},"podSecurityContext":{"fsGroup":100,"fsGroupChangePolicy":"OnRootMismatch","seccompProfile":{"type":"RuntimeDefault"},"supplementalGroups":[26,303]}}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    env:
      PGID: 100
      PUID: 1000
      TZ: America/Los_Angeles
    hostNetwork: true
    image:
      imagePullPolicy: Always
      repository: ghcr.io/linuxserver/plex
      tag: latest
    ingress:
      main:
        enabled: false
    persistence:
      audiobooks:
        enabled: true
        hostPath: /data/media/audiobooks
        mountPath: /audiobooks
        type: hostPath
      config:
        enabled: true
        hostPath: /data/general/config/plex
        mountPath: /config
        type: hostPath
      movies:
        enabled: true
        hostPath: /data/media/movies
        mountPath: /movies
        type: hostPath
      transcode:
        enabled: true
        medium: Memory
        type: emptyDir
      tv:
        enabled: true
        hostPath: /data/media/tv
        mountPath: /tv
        type: hostPath
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/plex: unconfined
    podSecurityContext:
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
      - 26
      - 303
