apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: qbittorrent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    additionalContainers:
      gluetun:
        env:
        - name: TZ
          value: America/Los_Angeles
        - name: VPN_SERVICE_PROVIDER
          value: airvpn
        - name: VPN_TYPE
          value: wireguard
        - name: WIREGUARD_ADDRESSES
          value: 10.184.150.109/32,fd7d:76ee:e68f:a993:38c6:c8f3:5d35:8c9/128
        - name: SERVER_COUNTRIES
          value: Switzerland
        - name: FIREWALL_VPN_INPUT_PORTS
          value: "21133"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: 120s
        envFrom:
        - secretRef:
            name: qbittorrent
        image: qmcgaw/gluetun
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
    env:
      PGID: 100
      PUID: 1000
      QBT_TORRENTING_PORT: "21133"
      TZ: America/Los_Angeles
    image:
      imagePullPolicy: Always
      repository: ghcr.io/hotio/qbittorrent
      tag: latest
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        hostPath: /data/general/config/qbittorrent
        mountPath: /config
        type: hostPath
      downloads:
        enabled: true
        hostPath: /data/torrents/qbittorrent
        mountPath: /downloads/qbittorrent
        type: hostPath
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/qbittorrent: unconfined
      operator.1password.io/item-name: qbittorrent
      operator.1password.io/item-path: vaults/pbcloud/items/qbittorrent
    podSecurityContext:
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      capabilities: {}
