apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  name: readarr
  namespace: media
spec:
  routes:
  - services:
    - name: readarr
      port: 8787
  virtualhost:
    fqdn: readarr.xnauts.net
    tls:
      secretName: cert-manager/xnauts-net-tls
