apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  name: bazarr
  namespace: media
spec:
  routes:
  - services:
    - name: bazarr
      port: 6767
  virtualhost:
    fqdn: bazarr.xnauts.net
    tls:
      secretName: cert-manager/xnauts-net-tls
