apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  name: prowlarr
  namespace: media
spec:
  routes:
  - services:
    - name: prowlarr
      port: 9696
  virtualhost:
    fqdn: prowlarr.xnauts.net
    tls:
      secretName: cert-manager/xnauts-net-tls
