apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  name: qbittorrent
  namespace: media
spec:
  routes:
  - services:
    - name: qbittorrent
      port: 8080
  virtualhost:
    fqdn: qbittorrent.xnauts.net
    tls:
      secretName: cert-manager/xnauts-net-tls
