apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"onepassword.com/v1","kind":"OnePasswordItem","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"discord-url","namespace":"flux-system"},"spec":{"itemPath":"vaults/pbcloud/items/discord-flux"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: discord-url
  namespace: flux-system
spec:
  itemPath: vaults/pbcloud/items/discord-flux
