apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pbcloud
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: main
  url: https://github.com/pbar1/pbcloud
