apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta2","kind":"HelmRepository","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"1password","namespace":"flux-system"},"spec":{"interval":"24h","provider":"generic","timeout":"60s","url":"https://1password.github.io/connect-helm-charts"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: 1password
  namespace: flux-system
spec:
  interval: 24h
  provider: generic
  timeout: 60s
  url: https://1password.github.io/connect-helm-charts
