apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks
  namespace: flux-system
spec:
  interval: 24h
  provider: generic
  timeout: 60s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
