apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta2","kind":"GitRepository","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"24h0m0s","ref":{"branch":"main"},"secretRef":{"name":"flux-system"},"url":"ssh://git@github.com/pbar1/pbcloud"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: flux-system
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/pbar1/pbcloud
