apiVersion: v1
data:
  DOMAIN: xnauts.net
  EMAIL: piercebartine@gmail.com
  NETWORK_CIDR: 192.168.0.0/23
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DOMAIN":"xnauts.net","EMAIL":"piercebartine@gmail.com","NETWORK_CIDR":"192.168.0.0/23"},"kind":"ConfigMap","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"cluster-settings","namespace":"flux-system"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: cluster-settings
  namespace: flux-system
