version: '3'

env:
  GIT_ROOT:
    sh: 2>/dev/null git rev-parse --show-toplevel || sl root
  PULUMI_CONFIG_PASSPHRASE: ""
  PULUMI_SKIP_UPDATE_CHECK: true

tasks:
  default: task --list

  build:
    desc: Build source into materialized configs
    cmds:
    - rm -rf materialized
    - bash scripts/materialize.sh
    # TODO: The following are only for clowntown purposes until migration complete:
    - rm -rf clusters/tec/media
    - cp -r materialized/k8s/tec/media clusters/tec/media
    - rm -rf clusters/tec/flux-system/helm-repos
    - cp -r materialized/k8s/tec/flux-system/helm-repos clusters/tec/flux-system/helm-repos
    - rm -rf clusters/tec/unifi
    - cp -r materialized/k8s/tec/unifi clusters/tec/unifi

  # FIXME: Convenience putting this here, also exists in clusters/tec
  sync:
    desc: Sync Flux with this Git repo
    cmds:
    - flux reconcile source git flux-system

  pulumi:crds:
    desc: Import Kubernetes CRDs to Pulumi
    cmds:
    - rm -rf source/lib/crds/.clean
    - fd . source/lib/crds/.import/ -e yaml -x sh -c 'out=$(echo "{}" | sed "s|\.import|\.clean|g"); mkdir -p $(dirname $out); node scripts/crdclean.ts {} > $out'
    - fd . source/lib/crds/.clean/ -t d -x sh -c 'name=$(basename {}); crd2pulumi --nodejs --nodejsName=$name --nodejsPath=source/lib/crds/$name {}/*.yaml'


  pulumi:up:
    desc: Build with Pulumi
    cmds:
    - pulumi up

  pulumi:resources:
    desc: Show Pulumi resource tree
    cmds:
    - pulumi stack
