version: "3"

tasks:
  default: task --list

  init:
    aliases: [ "i", "bootstrap" ]
    desc: Initialize remote state
    cmds:
    - terraform -chdir=clusters/tec init

  plan:
    aliases: [ "p", "diff" ]
    desc: Plan changes
    deps:
    - init
    cmds:
    - terraform -chdir=clusters/tec plan

  apply:
    aliases: [ "a" ]
    desc: Apply changes
    cmds:
    - terraform -chdir=clusters/tec apply

  tec:
    desc: Run arbitrary Terraform commands on `clusters/tec`
    cmds:
    - terraform -chdir=clusters/tec {{.CLI_ARGS}}
