apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 24h
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  values:
    image:
      tag: latest
      pullPolicy: Always

    env:
      TZ: America/Los_Angeles

    hostNetwork: true

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 44
      - 109
      seccompProfile:
        type: RuntimeDefault

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/general/config/plex
        mountPath: /config
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      tv:
        enabled: true
        type: hostPath
        hostPath: /data/media/tv
        mountPath: /tv
      movies:
        enabled: true
        type: hostPath
        hostPath: /data/media/movies
        mountPath: /movies
      audiobooks:
        enabled: true
        type: hostPath
        hostPath: /data/media/audiobooks
        mountPath: /audiobooks
