apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 24h
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/plex
      tag: latest
      pullPolicy: Always

    env:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 100

    hostNetwork: true

    podSecurityContext:
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      # $ cat /etc/group | grep "video\|render"
      # video:x:26:
      # render:x:303:
      supplementalGroups:
      - 26
      - 303
      seccompProfile:
        type: RuntimeDefault

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/general/config/plex
        mountPath: /config
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      tv:
        enabled: true
        type: hostPath
        hostPath: /data/media/tv
        mountPath: /tv
      movies:
        enabled: true
        type: hostPath
        hostPath: /data/media/movies
        mountPath: /movies
      audiobooks:
        enabled: true
        type: hostPath
        hostPath: /data/media/audiobooks
        mountPath: /audiobooks

    # resources:
    #   limits:
    #     amd.com/gpu: 1
