apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 24h
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  values:
    image:
      tag: latest
      pullPolicy: Always

    env:
      TZ: America/Los_Angeles

    podAnnotations:
      # FIXME: failed to get container spec opts: failed to generate apparmor spec opts: apparmor is not supported
      container.apparmor.security.beta.kubernetes.io/sonarr: unconfined

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      capabilities:
        drop:
        - all
      seccompProfile:
        type: RuntimeDefault

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/general/config/sonarr
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /data/media/tv
        mountPath: /tv
      downloads:
        enabled: true
        type: hostPath
        hostPath: /data/torrents/transmission
        mountPath: /downloads

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: "sonarr.${DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${DOMAIN}"
          secretName: sonarr-tls

    # TODO: Enable
    metrics:
      enabled: false
