apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: media-qbittorrent-c85a0884
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        operator.1password.io/item-name: qbittorrent
        operator.1password.io/item-path: vaults/pbcloud/items/qbittorrent
      labels:
        cdk8s.io/metadata.addr: media-qbittorrent-c85a0884
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: QBT_TORRENTING_PORT
              value: "21133"
          image: ghcr.io/hotio/qbittorrent:latest
          imagePullPolicy: Always
          name: qbittorrent
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
          volumeMounts:
            - mountPath: /downloads
              name: downloads
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
        - env:
            - name: VPN_SERVICE_PROVIDER
              value: airvpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_ADDRESSES
              value: 10.184.150.109/32,fd7d:76ee:e68f:a993:38c6:c8f3:5d35:8c9/128
            - name: SERVER_COUNTRIES
              value: Switzerland
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "21133"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: 120s
          envFrom:
            - secretRef:
                name: qbittorrent
          image: qmcgaw/gluetun:latest
          imagePullPolicy: Always
          name: main
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/torrents
            type: ""
          name: downloads
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /zssd/general/config/qbittorrent
            type: ""
          name: config
