apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: media-bazarr-c83d26b1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: media-bazarr-c83d26b1
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          image: ghcr.io/hotio/bazarr:latest
          imagePullPolicy: Always
          name: bazarr
          ports:
            - containerPort: 6767
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6767
          volumeMounts:
            - mountPath: /tv
              name: tv
            - mountPath: /movies
              name: movies
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/media/tv
            type: ""
          name: tv
        - hostPath:
            path: /data/media/movies
            type: ""
          name: movies
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /zssd/general/config/bazarr
            type: ""
          name: config
