apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: media-plex-c847cd10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: media-plex-c847cd10
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          image: ghcr.io/linuxserver/plex
          imagePullPolicy: Always
          name: plex
          ports:
            - containerPort: 32400
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 32400
          volumeMounts:
            - mountPath: /tv
              name: tv
            - mountPath: /movies
              name: movies
            - mountPath: /audiobooks
              name: audiobooks
            - mountPath: /music
              name: music
            - mountPath: /youtube
              name: youtube
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
            - mountPath: /transcode
              name: transcode
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/media/tv
            type: ""
          name: tv
        - hostPath:
            path: /data/media/movies
            type: ""
          name: movies
        - hostPath:
            path: /data/media/audiobooks
            type: ""
          name: audiobooks
        - hostPath:
            path: /data/media/music
            type: ""
          name: music
        - hostPath:
            path: /data/media/youtube
            type: ""
          name: youtube
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /zssd/general/config/plex
            type: ""
          name: config
        - emptyDir:
            medium: Memory
          name: transcode
