apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: media-lidarr-c8bd7459
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: media-lidarr-c8bd7459
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          image: ghcr.io/hotio/lidarr:nightly
          imagePullPolicy: Always
          name: lidarr
          ports:
            - containerPort: 8686
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8686
          volumeMounts:
            - mountPath: /downloads
              name: downloads
            - mountPath: /recycle-bin
              name: recycle-bin
            - mountPath: /music
              name: music
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/torrents
            type: ""
          name: downloads
        - hostPath:
            path: /data/media/recycle-bin
            type: ""
          name: recycle-bin
        - hostPath:
            path: /data/media/music
            type: ""
          name: music
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /zssd/general/config/lidarr
            type: ""
          name: config
