apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 5055
      targetPort: 5055
  selector:
    cdk8s.io/metadata.addr: media-overseerr-c8d20cec
  type: ClusterIP
