apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 6767
      targetPort: 6767
  selector:
    cdk8s.io/metadata.addr: media-bazarr-c83d26b1
  type: ClusterIP
