apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 8989
      targetPort: 8989
  selector:
    cdk8s.io/metadata.addr: media-sonarr-c83de5a2
  type: ClusterIP
