apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 8191
      targetPort: 8191
  selector:
    cdk8s.io/metadata.addr: media-flaresolverr-c8fcffd7
  type: ClusterIP
