apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 7878
      targetPort: 7878
  selector:
    cdk8s.io/metadata.addr: media-lidarr-c8bd7459
  type: ClusterIP
