apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    cdk8s.io/metadata.addr: media-tautulli-c8d81988
  type: ClusterIP
