apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 32400
      targetPort: 32400
  selector:
    cdk8s.io/metadata.addr: media-plex-c847cd10
  type: ClusterIP
