apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 9696
      targetPort: 9696
  selector:
    cdk8s.io/metadata.addr: media-prowlarr-c8f293d1
  type: ClusterIP
