apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    cdk8s.io/metadata.addr: media-readarr-c81f5058
  type: ClusterIP
