apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  externalIPs: []
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    cdk8s.io/metadata.addr: media-qbittorrent-c85a0884
  type: ClusterIP
