apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  force: false
  interval: 24h
  path: ./materialized/knative-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
