apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    networking.knative.dev/ingress-provider: contour
  name: contour-certgen
  namespace: contour-internal
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
