apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "unifi-controller"
  namespace: "unifi"
spec:
  chart:
    spec:
      chart: "unifi-controller"
      sourceRef:
        kind: "HelmRepository"
        name: "geek-cookbook"
        namespace: "flux-system"
  interval: "24h"
  values:
    env:
      TZ: "America/Los_Angeles"
      UNIFI_GID: "100"
      UNIFI_UID: "1000"
    hostNetwork: true
    persistence:
      data:
        enabled: true
        hostPath: "/data/general/unifi"
        mountPath: "/unifi"
        type: "hostPath"