apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    logLevel: debug

    # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
    provider: cloudflare

    env:
    - name: CF_API_EMAIL
      value: "${EMAIL}"
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-credentials
          key: CF_API_KEY
