apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BAR: ENC[AES256_GCM,data:tfB6,iv:VQWIcMxzdIXqdyYO0gmPKzT6d9TowQsvmVKQCb7ok9A=,tag:r6eVdC7Wu/XBDzwVCcRoFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-12T03:40:49Z"
    mac: ENC[AES256_GCM,data:dEKCbeCaf+uiEoUiBi7DHL1L2mILXzufj6/F5JTo8qvEexbbq7bXzxcborFLPmyQP1V9Fc3k/vGhH7P6tMq0Pr06JxwVXxdEG+9ikBYsJIbVRenTNJ017ZsjeWzxrViaBzXdsbT18LMjtck7xTX+ErdGwqLoGwsYUYo7kN9qu6c=,iv:JpZUfwnMmoV//DZl4lA+7M6CNdTOxQ6LTQzoJB4F83A=,tag:sminQg+6oZG7WmcBTpKYSg==,type:str]
    pgp:
        - created_at: "2023-02-12T03:40:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ/+NJGA8hH/I/UunfcDgKuWyObS5eUVnE8Q8c3Z9WUoSUBV
            WwvknOgWnyx7K0vDVXDUkcfTnPhi9Vk7aGYTkKaDO+ts5gcxdZMmgCQ5WGkNRHmf
            FNttHOZBcPb3eA0+CRejOPh7KkxpprpwFAvExQltfDt9eHmJR6K0lvSxvCFcpWYS
            quA4eJyE3B52I+s125LAQydk21MF1KdR1LLvZbl9A1/IoHYXuKApaNztimoQtUtT
            4NXQ3ynwhpwGT/hva2erKMDby0hbesAVjZzf3fRKLzesxl8u5SDAhlZL0tyLFRBC
            L4/SS2jB2tPJJBLuaP6yePe/iI/Q9yCS504pds/GNkYvIBJIKbnLHvDQe4f9EjD3
            9/jwbTlRrrYAH4vqKqn2xj+kllZMGHscYfWKK+F2cD6eVQcm4K0l2CmUDbM1o8Oj
            dyVwrbKCBXjP02PkHmvtEq2jgeLzq515yFLcNWciSBqVDmtuZu/22o/MpkfLR9Th
            A5yXiImU4064F8JllAKe0wwt+rd5tgg28H1kY3cc1aLevf2v0ddsmqbfpcQdkOmB
            VobncxWq/nyAe0xPUzp+N1yswK5T+iS4DPEkjBrwzHjAaAm1d9WNErMuCPuJ3KZb
            eITE0f/12iF0vg4koz3gs9lrtDozBjp3uB+/pH4vOXtfx5g3vmG6Q6M4xESlpV7U
            aAEJAhAeJHCo+dj/ZDR3m925P8D/jBqXyLB0qH/wD5gQ+e0PjJBc1a/9CZiJcakE
            lEAQym57ob022cHIkZm+SszgHYmaw+/eOyP9FrlA6InnFvuzGy+51cxe045jYL78
            +HH/SjY7yrXC
            =lJn/
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
