apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BAR: ENC[AES256_GCM,data:Nxnd,iv:itA8zR5qHSz+aB/shfb9R09CfnRihNm+mI4m6HOu5X8=,tag:ytM6DHgjSp4KfawKmGxJTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-10T05:04:12Z"
    mac: ENC[AES256_GCM,data:ipv/dcTSFpIBsqEqQJzy3JZh28V53z8fL1gPjWvrXP+9aUIa9jws6AO/2kdCYzB+eCUU0yP0S7YwL8QTwBRsAgZTIH5l1envPutXrGZKPXMAimHVlp+htjzJ/hwQNWv1l/J5blk4G4EWXc6tMFY1b8KI9/oZrQlv3d+PUsIg1hk=,iv:CiRKthAlXGFDDi1571gJRUbG5a4ymJgsdeDrAEvlcoM=,tag:XTEGaFs4czulOJwSHNJk9w==,type:str]
    pgp:
        - created_at: "2023-02-10T05:04:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ//dOFfXdHx6QJ7wUd7A3kT5DdQnZBsJP+TDsgns60kFqtg
            L7ViT/ismtuUmz14SuqTIRPShZosTv+9vp4exvm75ziY2wYRCrwkbXYyR4CjP2op
            0ythiI0VcpsJnUski7QDGk3gxlV/o74AP5fTkJaMF1E3mXULUmQlNAwc9jtJbrzq
            4suYUnWW7px5HW+KX3e8O8lf6kCftcTlwYP6oF1D1KLf3L2980LsI6xoKWHjuEA4
            ZFF1BitVC+a8wZVb9kDXTxwkWVWdQAgfM3jFI+qxdsp5gdRcI4ESYjrsFlZ+EeH+
            sy/lDZVw4kgtsl4xyhQ8lSng4JYPVFNNa0Qv5efZEqs6b2ITbTUIYRDaCbQfP7yD
            /PE4CJrNBYU8PIbMO/yGvUgjQs2pIhhqEFXR7sJaRZvj06UbebLdl8n3bFmLxGKY
            xnbrdWkqIrsOFnQZQww3oZ+FFIOlmWcQoaskFcA6wHe9E2uW3ghNphlYd3BDL0pS
            3V4fd3suE1OE80dMGbj0K0w5nuC8hQB66ScRIHzYalp0zq6Q7IYGR+d+S+Qv/+jX
            GhOSGOB3aRmKcFubOl3lAo+Hox3jKFmD1zjbB20Avbh2N4AuK2MQwP7E706Jt+sk
            7DST0NXN9w+3O1ENVXqPgEt5F6PxjwYaDaAg2FziFCXcIZiUuARg8VnTNSwTBgjU
            aAEJAhAHOvJdgVST4fYVm+95motPdiUDl5fixK2TY++I7LjRTuw8MvG5WBC5P/2J
            5pCXVlBp9i9EV5zwUSI+Nh/+9IiFkpyHB64+eZ0vG0TdoMBUPtAXILmiFV0otTmt
            JsCJZ5/1P3HO
            =xOX1
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
