apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:CvWRBDj8mijBhS+6EPjkJiQYLzpkcWI03eV/1HfM7RF8dJ29D+/o9cFlvO8isuuze0HuE+20sndVz0oEWMmBZl5h2kXytTAg6UMcROSw1AL26WeJhlPyp7FS+hEmVEEZqfRoE0NaTwF6Py5cu7RUf/Ss4loITyiZ7g==,iv:630SzWSh14CZKdUQOJX66KgsawnGHtMNj0w5sOeqn6E=,tag:MwwQekzcm3vxGSmsXwbp+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-10T06:25:43Z"
    mac: ENC[AES256_GCM,data:esRzSh/9WBMaE3F+xstc6FJVPJa4n36uhb/HqZCBnrwnqJ74qQos++nT4oAXrok7fXbWmiBLMVI3CjjoXbjR1feAuQuR4Sk7F1vz0IRL7IDIVrivjE+Ji3YgoWva9qb/miXTLI+vwbHBYSnoRo3mg1HlpJEESVfw7NfRoLtur3g=,iv:UNi1D3LMEm56eJ0vFwtIQ7YmOwtdbW4f7MY0t7/VsJI=,tag:2DoHQvjcblerX4SSH2vVCw==,type:str]
    pgp:
        - created_at: "2023-02-10T06:25:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ//cduj7CeJMQxi3EhqjAmdGfZlUbok3Xp88pKNtUmBlFUc
            +k0i2l28Nwnndlq7YtQ1BwcqPNvkLE5d/60IksSmCvzddoVVB9g5xsgp0mW5jYSH
            kiTekm1gADYKACZ3AkYoy1CkX0uOtNPal2Mb0CrHXHXD1q0iviJEAmibilQBZXfj
            1wD3Nj6swvwSwZXZbMXGC+Wi+HV49E4ii+pvxCbOthuqt8Y1aVmACTarRUhDzYQR
            035RfLdUpA41p//AaPf0Uak4h653TyfNopleG9X6Asy3Kzqd5Xx4CQh0UygQIbtO
            5O34KQCsRnSE2NhkFA66OLoq3NzRIrxd27LXlQ4Loyreeohsql4cURk8rKDpJqsC
            7sQR3luOnZIJSSeDssd/Evp3cA0WOXun5CBZM7AvF0YNKK0IcRXYjBSySIWgNdvy
            9B5NIuXN++iK3F+1FoTaAjYVXUwaJzZDxb12rpW9j2VZc1o70NUnnaVi85xnABcr
            D7Bw69Xq9byFKu6p3G3FaTWWQqDNRDtmsrvT6YEpEIJRjOTVCWkpy0pxOXkVgZeM
            uvbHHZFGq3K9G+DbOUeC9soFbJFR4QrvRK7LXLDiDYJrVrEs0kdcnOG9HHHax04h
            J72jOSsUKPyoCEkIDnzR1BfCxlww7ynswgrG+BOSuVT6+4i291fIajqG28ITYsPU
            ZgEJAhDNt3TgsfkiYNH7Q0tc3PeHbne2cylgVVYl59ZcrupAUOW6pmzRfCCylZqR
            SMoMo5po0LS45zUHXWbqZzNpmMHiB/o6VgYScV87Lw4EnVXkUoaVUb97woo7Ln0p
            bTbcgkYkoA==
            =X6DR
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
