apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    clientID: ENC[AES256_GCM,data:MPCgu73azBkpS5c4wTSVgZbElanXbPdiRNjP7Vj0RGk=,iv:rQuVZJ3QWuqbfmbnaIEgv20SSKW8HymJwoIbPjcn/us=,tag:lu0ccLUfpwiT/6UslsHWxw==,type:str]
    clientSecret: ENC[AES256_GCM,data:eE1FpJEcuQfxYhcNzb755jwYTRfYwWzRAGU/yqHyYkO8Usls5yyLHI6X+NU7MfzPd57J/Yj6tlRKX+VSS1Af+w==,iv:d6Rli2E60wOyhS6r2lt2VZ1MhDCbkqy6CUJoD+opBfg=,tag:AFMKUADVzKTvvDDRODGITg==,type:str]
    issuerURL: ENC[AES256_GCM,data:UJaqb5/jG3hE2BnlTek1X+7SSvB4UUv/+6lltXiTGZeDzAxeg66OTh2W,iv:PnX0Zn0SUpP3eLRPlgQuapciKQbt3YB8ukiarqAFdwg=,tag:/JORQgmYyizNotL9UkW2Nw==,type:str]
    redirectURL: ENC[AES256_GCM,data:XnSZyjNaDNH6d1UoWrMNG1Ts3WT3t1oRFHn/SKZBRNBW1rkHAtGlfLw=,iv:FE1cmwnp60dDi8P3vBRcJLRFAKm3BdN12PzKI7g9ICc=,tag:Dr3dI7mPcyIqk9vD0bXZ6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-11T18:10:50Z"
    mac: ENC[AES256_GCM,data:VkqCo8LP2Pf17/ino3aP780Utbhpc27WgBnKD1WNaWNtlXFEmwUVfYQ3SwTP/AorNSwUH2F2ABeiodT2NS6Wj2VbWq/wmUuoGUkyjsEhbcLDbdcK5cA+gWizz+GbrKKdp3BCCCzf2W2INC+3zUOOjJcXpOZ6sjfZjS5TVTi162E=,iv:nC5JgeMxOYhCa591FC/sfmvJuz49GzXi9G6aE+5O9Xk=,tag:zbODdLdZchQhF3s4Xw3n1A==,type:str]
    pgp:
        - created_at: "2023-02-11T18:10:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ//WUcvOYs7XIJZiItBA34hSWNT9+fCk8Uj1NTdicdIbqPW
            dt29hFNDlMJGeJcsbKLDkhR8w9doqvX6Up7ULVEW/QBRtSDjluRTqONWXxLH1K30
            26EAvS/Ot6xiygjU6KxHJnxQjAQ0/De4mDf/Qwt8dv3MrdgEnqxOw7S0OxMU8+OV
            IvTMH7ijwbUWy4O/NB7Jshc4DEnUHuUIIfV6swrfcf+RAfNr02RMhk5MHO4jWfR/
            tpBaHO+j/riXryIEzriLRq7FljXFCLk7O8qSk1sljcFBy/sYWaNYAy5oRKNmjCrO
            0AYH1qr08t4Mcb6/mtVEmaybYEWSj7WGQKUgKkB6VESUF6UWMFIeV5YUxOWBgOce
            Jbge0b9sUxAbtBcLKBfVBpR58xdTTWc+ASYyZlmOsAoJe+/1aFG2YXS/i57VHks0
            ehBqg2l3qO0Bdl3SggCN6svHjsxLtKcjbIN4oM+qWz4OmR/nUKxnxFM/9j567Gy6
            Ge9q9j2xAqygo92MPjWAt2SPByEpoKeh3PPv21CrRYRSOoI4m6tta/fi1/lB1nco
            Jr6HqVIFrasZoJNSSqZspVSzI0tzDXCLXBtiJ/yLKN5u81zWQau3I94KGij8XC+m
            GzJ3aNACfjo9/RRQpTy+gw0ZAsIUhqNtdSFL9fSp1dDp4EXwoh2juo2Xbx9kz7zU
            aAEJAhDzoL7lVuBMyRCVH5NtShCD1p6VWxNpJLDdHz4Wmx9YHEkNt1hVVJGNqhdX
            Zzu1DWQESx1ik4Fas4S69UDqaxYmS5Ep10uumlx+Schu6krnze4kERs+CU+u84bK
            LW8dEEPMMQjG
            =u4i4
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
