apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"helm.toolkit.fluxcd.io/v2beta1","kind":"HelmRelease","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"gitea","namespace":"gitea"},"spec":{"chart":{"spec":{"chart":"gitea","reconcileStrategy":"ChartVersion","sourceRef":{"kind":"HelmRepository","name":"gitea","namespace":"flux-system"},"version":"*"}},"interval":"24h","values":{"gitea":{"config":{"database":{"DB_TYPE":"sqlite3"},"server":{"DISABLE_SSH":true,"START_SSH_SERVER":false}}},"image":{"pullPolicy":"IfNotPresent","rootless":true},"ingress":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-production","traefik.ingress.kubernetes.io/router.entrypoints":"websecure"},"enabled":true,"hosts":[{"host":"gitea.xnauts.net","paths":[{"path":"/","pathType":"Prefix"}]}],"tls":[{"hosts":["gitea.xnauts.net"],"secretName":"gitea-tls"}]},"memcached":{"enabled":false},"persistence":{"enabled":true,"storageClass":"local-path"},"postgresql":{"enabled":false}}}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    gitea:
      config:
        database:
          DB_TYPE: sqlite3
        server:
          DISABLE_SSH: true
          START_SSH_SERVER: false
    image:
      pullPolicy: IfNotPresent
      rootless: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      enabled: true
      hosts:
      - host: gitea.xnauts.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - gitea.xnauts.net
        secretName: gitea-tls
    memcached:
      enabled: false
    persistence:
      enabled: true
      storageClass: local-path
    postgresql:
      enabled: false
