// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

import {ObjectMeta} from "../meta/v1";

export namespace networking {
    export namespace v1alpha1 {
        /**
         * TunnelSpec defines the desired state of Tunnel
         */
        export interface ClusterTunnelSpecArgs {
            /**
             * Cloudflare Credentials
             */
            cloudflare?: pulumi.Input<inputs.networking.v1alpha1.ClusterTunnelSpecCloudflareArgs>;
            /**
             * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
             */
            existingTunnel?: pulumi.Input<inputs.networking.v1alpha1.ClusterTunnelSpecExistingTunnelArgs>;
            /**
             * FallbackTarget speficies the target for requests that do not match an ingress. Defaults to http_status:404
             */
            fallbackTarget?: pulumi.Input<string>;
            /**
             * Image sets the Cloudflared Image to use. Defaults to the image set during the release of the operator.
             */
            image?: pulumi.Input<string>;
            /**
             * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
             */
            newTunnel?: pulumi.Input<inputs.networking.v1alpha1.ClusterTunnelSpecNewTunnelArgs>;
            /**
             * NoTlsVerify disables origin TLS certificate checks when the endpoint is HTTPS.
             */
            noTlsVerify?: pulumi.Input<boolean>;
            /**
             * OriginCaPool speficies the secret with tls.crt (and other certs as needed to be referred in the service annotation) of the Root CA to be trusted when sending traffic to HTTPS endpoints
             */
            originCaPool?: pulumi.Input<string>;
            /**
             * Size defines the number of Daemon pods to run for this tunnel
             */
            size?: pulumi.Input<number>;
        }
        /**
         * clusterTunnelSpecArgsProvideDefaults sets the appropriate defaults for ClusterTunnelSpecArgs
         */
        export function clusterTunnelSpecArgsProvideDefaults(val: ClusterTunnelSpecArgs): ClusterTunnelSpecArgs {
            return {
                ...val,
                cloudflare: (val.cloudflare ? pulumi.output(val.cloudflare).apply(inputs.networking.v1alpha1.clusterTunnelSpecCloudflareArgsProvideDefaults) : undefined),
                fallbackTarget: (val.fallbackTarget) ?? "http_status:404",
                image: (val.image) ?? "cloudflare/cloudflared:2022.12.1",
                noTlsVerify: (val.noTlsVerify) ?? false,
                size: (val.size) ?? 1,
            };
        }

        /**
         * Cloudflare Credentials
         */
        export interface ClusterTunnelSpecCloudflareArgs {
            /**
             * Key in the secret to use for Cloudflare API Key, defaults to CLOUDFLARE_API_KEY. Needs Email also to be provided. For Delete operations for new tunnels only, or as an alternate to API Token
             */
            CLOUDFLARE_API_KEY?: pulumi.Input<string>;
            /**
             * Key in the secret to use for Cloudflare API token, defaults to CLOUDFLARE_API_TOKEN
             */
            CLOUDFLARE_API_TOKEN?: pulumi.Input<string>;
            /**
             * Key in the secret to use as credentials.json for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_FILE?: pulumi.Input<string>;
            /**
             * Key in the secret to use as tunnel secret for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET?: pulumi.Input<string>;
            /**
             * Account ID in Cloudflare. AccountId and AccountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountId?: pulumi.Input<string>;
            /**
             * Account Name in Cloudflare. AccountName and AccountId cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountName?: pulumi.Input<string>;
            /**
             * Cloudflare Domain to which this tunnel belongs to
             */
            domain?: pulumi.Input<string>;
            /**
             * Email to use along with API Key for Delete operations for new tunnels only, or as an alternate to API Token
             */
            email?: pulumi.Input<string>;
            /**
             * Secret containing Cloudflare API key/token
             */
            secret?: pulumi.Input<string>;
        }
        /**
         * clusterTunnelSpecCloudflareArgsProvideDefaults sets the appropriate defaults for ClusterTunnelSpecCloudflareArgs
         */
        export function clusterTunnelSpecCloudflareArgsProvideDefaults(val: ClusterTunnelSpecCloudflareArgs): ClusterTunnelSpecCloudflareArgs {
            return {
                ...val,
                CLOUDFLARE_API_KEY: (val.CLOUDFLARE_API_KEY) ?? "CLOUDFLARE_API_KEY",
                CLOUDFLARE_API_TOKEN: (val.CLOUDFLARE_API_TOKEN) ?? "CLOUDFLARE_API_TOKEN",
                CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_FILE) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_FILE",
                CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET",
            };
        }

        /**
         * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
         */
        export interface ClusterTunnelSpecExistingTunnelArgs {
            /**
             * Existing Tunnel ID to run on. Tunnel ID and Tunnel Name cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            id?: pulumi.Input<string>;
            /**
             * Existing Tunnel name to run on. Tunnel Name and Tunnel ID cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            name?: pulumi.Input<string>;
        }

        /**
         * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
         */
        export interface ClusterTunnelSpecNewTunnelArgs {
            /**
             * Tunnel name to create on Cloudflare.
             */
            name?: pulumi.Input<string>;
        }

        /**
         * TunnelStatus defines the observed state of Tunnel
         */
        export interface ClusterTunnelStatusArgs {
            accountId: pulumi.Input<string>;
            tunnelId: pulumi.Input<string>;
            tunnelName: pulumi.Input<string>;
            zoneId: pulumi.Input<string>;
        }

        /**
         * TunnelBindingStatus defines the observed state of TunnelBinding
         */
        export interface TunnelBindingStatusArgs {
            /**
             * To show on the kubectl cli
             */
            hostnames: pulumi.Input<string>;
            services: pulumi.Input<pulumi.Input<inputs.networking.v1alpha1.TunnelBindingStatusServicesArgs>[]>;
        }

        /**
         * ServiceInfo stores the Hostname and Target for each service
         */
        export interface TunnelBindingStatusServicesArgs {
            /**
             * FQDN of the service
             */
            hostname: pulumi.Input<string>;
            /**
             * Target for cloudflared
             */
            target: pulumi.Input<string>;
        }

        /**
         * TunnelBindingSubject defines the subject TunnelBinding connects to the Tunnel
         */
        export interface TunnelBindingSubjectsArgs {
            /**
             * Kind can be Service
             */
            kind?: pulumi.Input<string>;
            name: pulumi.Input<string>;
            spec?: pulumi.Input<inputs.networking.v1alpha1.TunnelBindingSubjectsSpecArgs>;
        }
        /**
         * tunnelBindingSubjectsArgsProvideDefaults sets the appropriate defaults for TunnelBindingSubjectsArgs
         */
        export function tunnelBindingSubjectsArgsProvideDefaults(val: TunnelBindingSubjectsArgs): TunnelBindingSubjectsArgs {
            return {
                ...val,
                kind: (val.kind) ?? "Service",
                spec: (val.spec ? pulumi.output(val.spec).apply(inputs.networking.v1alpha1.tunnelBindingSubjectsSpecArgsProvideDefaults) : undefined),
            };
        }

        export interface TunnelBindingSubjectsSpecArgs {
            /**
             * CaPool trusts the CA certificate referenced by the key in the secret specified in tunnel.spec.originCaPool. tls.crt is trusted globally and does not need to be specified. Only useful if the protocol is HTTPS.
             */
            caPool?: pulumi.Input<string>;
            /**
             * Fqdn specifies the DNS name to access this service from. Defaults to the service.metadata.name + tunnel.spec.domain. If specifying this, make sure to use the same domain that the tunnel belongs to. This is not validated and used as provided
             */
            fqdn?: pulumi.Input<string>;
            /**
             * NoTlsVerify disables TLS verification for this service. Only useful if the protocol is HTTPS.
             */
            noTlsVerify?: pulumi.Input<boolean>;
            /**
             * Protocol specifies the protocol for the service. Should be one of http, https, tcp, udp, ssh or rdp. Defaults to http, with the exceptions of https for 443, smb for 139 and 445, rdp for 3389 and ssh for 22 if the service has a TCP port. The only available option for a UDP port is udp, which is default.
             */
            protocol?: pulumi.Input<string>;
            /**
             * ProxyAddress configures the listen address for that proxy
             */
            proxyAddress?: pulumi.Input<string>;
            /**
             * ProxyPort configures the listen port for that proxy
             */
            proxyPort?: pulumi.Input<number>;
            /**
             * ProxyType configures the proxy type.
             */
            proxyType?: pulumi.Input<string>;
            /**
             * Target specified where the tunnel should proxy to. Defaults to the form of <protocol>://<service.metadata.name>.<service.metadata.namespace>.svc:<port>
             */
            target?: pulumi.Input<string>;
        }
        /**
         * tunnelBindingSubjectsSpecArgsProvideDefaults sets the appropriate defaults for TunnelBindingSubjectsSpecArgs
         */
        export function tunnelBindingSubjectsSpecArgsProvideDefaults(val: TunnelBindingSubjectsSpecArgs): TunnelBindingSubjectsSpecArgs {
            return {
                ...val,
                noTlsVerify: (val.noTlsVerify) ?? false,
                proxyAddress: (val.proxyAddress) ?? "127.0.0.1",
                proxyPort: (val.proxyPort) ?? 0,
                proxyType: (val.proxyType) ?? "",
            };
        }

        /**
         * TunnelRef defines the Tunnel TunnelBinding connects to
         */
        export interface TunnelBindingTunnelRefArgs {
            /**
             * DisableDNSUpdates disables the DNS updates on Cloudflare, just managing the configs. Assumes the DNS entries are manually added.
             */
            disableDNSUpdates?: pulumi.Input<boolean>;
            /**
             * Kind can be Tunnel or ClusterTunnel
             */
            kind: pulumi.Input<string>;
            /**
             * Name of the tunnel resource
             */
            name: pulumi.Input<string>;
        }

        /**
         * TunnelSpec defines the desired state of Tunnel
         */
        export interface TunnelSpecArgs {
            /**
             * Cloudflare Credentials
             */
            cloudflare?: pulumi.Input<inputs.networking.v1alpha1.TunnelSpecCloudflareArgs>;
            /**
             * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
             */
            existingTunnel?: pulumi.Input<inputs.networking.v1alpha1.TunnelSpecExistingTunnelArgs>;
            /**
             * FallbackTarget speficies the target for requests that do not match an ingress. Defaults to http_status:404
             */
            fallbackTarget?: pulumi.Input<string>;
            /**
             * Image sets the Cloudflared Image to use. Defaults to the image set during the release of the operator.
             */
            image?: pulumi.Input<string>;
            /**
             * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
             */
            newTunnel?: pulumi.Input<inputs.networking.v1alpha1.TunnelSpecNewTunnelArgs>;
            /**
             * NoTlsVerify disables origin TLS certificate checks when the endpoint is HTTPS.
             */
            noTlsVerify?: pulumi.Input<boolean>;
            /**
             * OriginCaPool speficies the secret with tls.crt (and other certs as needed to be referred in the service annotation) of the Root CA to be trusted when sending traffic to HTTPS endpoints
             */
            originCaPool?: pulumi.Input<string>;
            /**
             * Size defines the number of Daemon pods to run for this tunnel
             */
            size?: pulumi.Input<number>;
        }
        /**
         * tunnelSpecArgsProvideDefaults sets the appropriate defaults for TunnelSpecArgs
         */
        export function tunnelSpecArgsProvideDefaults(val: TunnelSpecArgs): TunnelSpecArgs {
            return {
                ...val,
                cloudflare: (val.cloudflare ? pulumi.output(val.cloudflare).apply(inputs.networking.v1alpha1.tunnelSpecCloudflareArgsProvideDefaults) : undefined),
                fallbackTarget: (val.fallbackTarget) ?? "http_status:404",
                image: (val.image) ?? "cloudflare/cloudflared:2022.12.1",
                noTlsVerify: (val.noTlsVerify) ?? false,
                size: (val.size) ?? 1,
            };
        }

        /**
         * Cloudflare Credentials
         */
        export interface TunnelSpecCloudflareArgs {
            /**
             * Key in the secret to use for Cloudflare API Key, defaults to CLOUDFLARE_API_KEY. Needs Email also to be provided. For Delete operations for new tunnels only, or as an alternate to API Token
             */
            CLOUDFLARE_API_KEY?: pulumi.Input<string>;
            /**
             * Key in the secret to use for Cloudflare API token, defaults to CLOUDFLARE_API_TOKEN
             */
            CLOUDFLARE_API_TOKEN?: pulumi.Input<string>;
            /**
             * Key in the secret to use as credentials.json for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_FILE?: pulumi.Input<string>;
            /**
             * Key in the secret to use as tunnel secret for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET?: pulumi.Input<string>;
            /**
             * Account ID in Cloudflare. AccountId and AccountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountId?: pulumi.Input<string>;
            /**
             * Account Name in Cloudflare. AccountName and AccountId cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountName?: pulumi.Input<string>;
            /**
             * Cloudflare Domain to which this tunnel belongs to
             */
            domain?: pulumi.Input<string>;
            /**
             * Email to use along with API Key for Delete operations for new tunnels only, or as an alternate to API Token
             */
            email?: pulumi.Input<string>;
            /**
             * Secret containing Cloudflare API key/token
             */
            secret?: pulumi.Input<string>;
        }
        /**
         * tunnelSpecCloudflareArgsProvideDefaults sets the appropriate defaults for TunnelSpecCloudflareArgs
         */
        export function tunnelSpecCloudflareArgsProvideDefaults(val: TunnelSpecCloudflareArgs): TunnelSpecCloudflareArgs {
            return {
                ...val,
                CLOUDFLARE_API_KEY: (val.CLOUDFLARE_API_KEY) ?? "CLOUDFLARE_API_KEY",
                CLOUDFLARE_API_TOKEN: (val.CLOUDFLARE_API_TOKEN) ?? "CLOUDFLARE_API_TOKEN",
                CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_FILE) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_FILE",
                CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET",
            };
        }

        /**
         * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
         */
        export interface TunnelSpecExistingTunnelArgs {
            /**
             * Existing Tunnel ID to run on. Tunnel ID and Tunnel Name cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            id?: pulumi.Input<string>;
            /**
             * Existing Tunnel name to run on. Tunnel Name and Tunnel ID cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            name?: pulumi.Input<string>;
        }

        /**
         * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
         */
        export interface TunnelSpecNewTunnelArgs {
            /**
             * Tunnel name to create on Cloudflare.
             */
            name?: pulumi.Input<string>;
        }

        /**
         * TunnelStatus defines the observed state of Tunnel
         */
        export interface TunnelStatusArgs {
            accountId: pulumi.Input<string>;
            tunnelId: pulumi.Input<string>;
            tunnelName: pulumi.Input<string>;
            zoneId: pulumi.Input<string>;
        }
    }
}
