// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

import {ObjectMeta} from "../meta/v1";

export namespace networking {
    export namespace v1alpha1 {
        /**
         * TunnelSpec defines the desired state of Tunnel
         */
        export interface ClusterTunnelSpec {
            /**
             * Cloudflare Credentials
             */
            cloudflare?: outputs.networking.v1alpha1.ClusterTunnelSpecCloudflare;
            /**
             * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
             */
            existingTunnel?: outputs.networking.v1alpha1.ClusterTunnelSpecExistingTunnel;
            /**
             * FallbackTarget speficies the target for requests that do not match an ingress. Defaults to http_status:404
             */
            fallbackTarget?: string;
            /**
             * Image sets the Cloudflared Image to use. Defaults to the image set during the release of the operator.
             */
            image?: string;
            /**
             * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
             */
            newTunnel?: outputs.networking.v1alpha1.ClusterTunnelSpecNewTunnel;
            /**
             * NoTlsVerify disables origin TLS certificate checks when the endpoint is HTTPS.
             */
            noTlsVerify?: boolean;
            /**
             * OriginCaPool speficies the secret with tls.crt (and other certs as needed to be referred in the service annotation) of the Root CA to be trusted when sending traffic to HTTPS endpoints
             */
            originCaPool?: string;
            /**
             * Size defines the number of Daemon pods to run for this tunnel
             */
            size?: number;
        }
        /**
         * clusterTunnelSpecProvideDefaults sets the appropriate defaults for ClusterTunnelSpec
         */
        export function clusterTunnelSpecProvideDefaults(val: ClusterTunnelSpec): ClusterTunnelSpec {
            return {
                ...val,
                cloudflare: (val.cloudflare ? outputs.networking.v1alpha1.clusterTunnelSpecCloudflareProvideDefaults(val.cloudflare) : undefined),
                fallbackTarget: (val.fallbackTarget) ?? "http_status:404",
                image: (val.image) ?? "cloudflare/cloudflared:2022.12.1",
                noTlsVerify: (val.noTlsVerify) ?? false,
                size: (val.size) ?? 1,
            };
        }

        /**
         * Cloudflare Credentials
         */
        export interface ClusterTunnelSpecCloudflare {
            /**
             * Key in the secret to use for Cloudflare API Key, defaults to CLOUDFLARE_API_KEY. Needs Email also to be provided. For Delete operations for new tunnels only, or as an alternate to API Token
             */
            CLOUDFLARE_API_KEY?: string;
            /**
             * Key in the secret to use for Cloudflare API token, defaults to CLOUDFLARE_API_TOKEN
             */
            CLOUDFLARE_API_TOKEN?: string;
            /**
             * Key in the secret to use as credentials.json for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_FILE?: string;
            /**
             * Key in the secret to use as tunnel secret for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET?: string;
            /**
             * Account ID in Cloudflare. AccountId and AccountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountId?: string;
            /**
             * Account Name in Cloudflare. AccountName and AccountId cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountName?: string;
            /**
             * Cloudflare Domain to which this tunnel belongs to
             */
            domain?: string;
            /**
             * Email to use along with API Key for Delete operations for new tunnels only, or as an alternate to API Token
             */
            email?: string;
            /**
             * Secret containing Cloudflare API key/token
             */
            secret?: string;
        }
        /**
         * clusterTunnelSpecCloudflareProvideDefaults sets the appropriate defaults for ClusterTunnelSpecCloudflare
         */
        export function clusterTunnelSpecCloudflareProvideDefaults(val: ClusterTunnelSpecCloudflare): ClusterTunnelSpecCloudflare {
            return {
                ...val,
                CLOUDFLARE_API_KEY: (val.CLOUDFLARE_API_KEY) ?? "CLOUDFLARE_API_KEY",
                CLOUDFLARE_API_TOKEN: (val.CLOUDFLARE_API_TOKEN) ?? "CLOUDFLARE_API_TOKEN",
                CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_FILE) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_FILE",
                CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET",
            };
        }

        /**
         * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
         */
        export interface ClusterTunnelSpecExistingTunnel {
            /**
             * Existing Tunnel ID to run on. Tunnel ID and Tunnel Name cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            id?: string;
            /**
             * Existing Tunnel name to run on. Tunnel Name and Tunnel ID cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            name?: string;
        }

        /**
         * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
         */
        export interface ClusterTunnelSpecNewTunnel {
            /**
             * Tunnel name to create on Cloudflare.
             */
            name?: string;
        }

        /**
         * TunnelStatus defines the observed state of Tunnel
         */
        export interface ClusterTunnelStatus {
            accountId: string;
            tunnelId: string;
            tunnelName: string;
            zoneId: string;
        }

        /**
         * TunnelBindingStatus defines the observed state of TunnelBinding
         */
        export interface TunnelBindingStatus {
            /**
             * To show on the kubectl cli
             */
            hostnames: string;
            services: outputs.networking.v1alpha1.TunnelBindingStatusServices[];
        }

        /**
         * ServiceInfo stores the Hostname and Target for each service
         */
        export interface TunnelBindingStatusServices {
            /**
             * FQDN of the service
             */
            hostname: string;
            /**
             * Target for cloudflared
             */
            target: string;
        }

        /**
         * TunnelBindingSubject defines the subject TunnelBinding connects to the Tunnel
         */
        export interface TunnelBindingSubjects {
            /**
             * Kind can be Service
             */
            kind?: string;
            name: string;
            spec?: outputs.networking.v1alpha1.TunnelBindingSubjectsSpec;
        }
        /**
         * tunnelBindingSubjectsProvideDefaults sets the appropriate defaults for TunnelBindingSubjects
         */
        export function tunnelBindingSubjectsProvideDefaults(val: TunnelBindingSubjects): TunnelBindingSubjects {
            return {
                ...val,
                kind: (val.kind) ?? "Service",
                spec: (val.spec ? outputs.networking.v1alpha1.tunnelBindingSubjectsSpecProvideDefaults(val.spec) : undefined),
            };
        }

        export interface TunnelBindingSubjectsSpec {
            /**
             * CaPool trusts the CA certificate referenced by the key in the secret specified in tunnel.spec.originCaPool. tls.crt is trusted globally and does not need to be specified. Only useful if the protocol is HTTPS.
             */
            caPool?: string;
            /**
             * Fqdn specifies the DNS name to access this service from. Defaults to the service.metadata.name + tunnel.spec.domain. If specifying this, make sure to use the same domain that the tunnel belongs to. This is not validated and used as provided
             */
            fqdn?: string;
            /**
             * NoTlsVerify disables TLS verification for this service. Only useful if the protocol is HTTPS.
             */
            noTlsVerify?: boolean;
            /**
             * Protocol specifies the protocol for the service. Should be one of http, https, tcp, udp, ssh or rdp. Defaults to http, with the exceptions of https for 443, smb for 139 and 445, rdp for 3389 and ssh for 22 if the service has a TCP port. The only available option for a UDP port is udp, which is default.
             */
            protocol?: string;
            /**
             * ProxyAddress configures the listen address for that proxy
             */
            proxyAddress?: string;
            /**
             * ProxyPort configures the listen port for that proxy
             */
            proxyPort?: number;
            /**
             * ProxyType configures the proxy type.
             */
            proxyType?: string;
            /**
             * Target specified where the tunnel should proxy to. Defaults to the form of <protocol>://<service.metadata.name>.<service.metadata.namespace>.svc:<port>
             */
            target?: string;
        }
        /**
         * tunnelBindingSubjectsSpecProvideDefaults sets the appropriate defaults for TunnelBindingSubjectsSpec
         */
        export function tunnelBindingSubjectsSpecProvideDefaults(val: TunnelBindingSubjectsSpec): TunnelBindingSubjectsSpec {
            return {
                ...val,
                noTlsVerify: (val.noTlsVerify) ?? false,
                proxyAddress: (val.proxyAddress) ?? "127.0.0.1",
                proxyPort: (val.proxyPort) ?? 0,
                proxyType: (val.proxyType) ?? "",
            };
        }

        /**
         * TunnelRef defines the Tunnel TunnelBinding connects to
         */
        export interface TunnelBindingTunnelRef {
            /**
             * DisableDNSUpdates disables the DNS updates on Cloudflare, just managing the configs. Assumes the DNS entries are manually added.
             */
            disableDNSUpdates?: boolean;
            /**
             * Kind can be Tunnel or ClusterTunnel
             */
            kind: string;
            /**
             * Name of the tunnel resource
             */
            name: string;
        }

        /**
         * TunnelSpec defines the desired state of Tunnel
         */
        export interface TunnelSpec {
            /**
             * Cloudflare Credentials
             */
            cloudflare?: outputs.networking.v1alpha1.TunnelSpecCloudflare;
            /**
             * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
             */
            existingTunnel?: outputs.networking.v1alpha1.TunnelSpecExistingTunnel;
            /**
             * FallbackTarget speficies the target for requests that do not match an ingress. Defaults to http_status:404
             */
            fallbackTarget?: string;
            /**
             * Image sets the Cloudflared Image to use. Defaults to the image set during the release of the operator.
             */
            image?: string;
            /**
             * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
             */
            newTunnel?: outputs.networking.v1alpha1.TunnelSpecNewTunnel;
            /**
             * NoTlsVerify disables origin TLS certificate checks when the endpoint is HTTPS.
             */
            noTlsVerify?: boolean;
            /**
             * OriginCaPool speficies the secret with tls.crt (and other certs as needed to be referred in the service annotation) of the Root CA to be trusted when sending traffic to HTTPS endpoints
             */
            originCaPool?: string;
            /**
             * Size defines the number of Daemon pods to run for this tunnel
             */
            size?: number;
        }
        /**
         * tunnelSpecProvideDefaults sets the appropriate defaults for TunnelSpec
         */
        export function tunnelSpecProvideDefaults(val: TunnelSpec): TunnelSpec {
            return {
                ...val,
                cloudflare: (val.cloudflare ? outputs.networking.v1alpha1.tunnelSpecCloudflareProvideDefaults(val.cloudflare) : undefined),
                fallbackTarget: (val.fallbackTarget) ?? "http_status:404",
                image: (val.image) ?? "cloudflare/cloudflared:2022.12.1",
                noTlsVerify: (val.noTlsVerify) ?? false,
                size: (val.size) ?? 1,
            };
        }

        /**
         * Cloudflare Credentials
         */
        export interface TunnelSpecCloudflare {
            /**
             * Key in the secret to use for Cloudflare API Key, defaults to CLOUDFLARE_API_KEY. Needs Email also to be provided. For Delete operations for new tunnels only, or as an alternate to API Token
             */
            CLOUDFLARE_API_KEY?: string;
            /**
             * Key in the secret to use for Cloudflare API token, defaults to CLOUDFLARE_API_TOKEN
             */
            CLOUDFLARE_API_TOKEN?: string;
            /**
             * Key in the secret to use as credentials.json for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_FILE?: string;
            /**
             * Key in the secret to use as tunnel secret for an existing tunnel, defaults to CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
             */
            CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET?: string;
            /**
             * Account ID in Cloudflare. AccountId and AccountName cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountId?: string;
            /**
             * Account Name in Cloudflare. AccountName and AccountId cannot be both empty. If both are provided, Account ID is used if valid, else falls back to Account Name.
             */
            accountName?: string;
            /**
             * Cloudflare Domain to which this tunnel belongs to
             */
            domain?: string;
            /**
             * Email to use along with API Key for Delete operations for new tunnels only, or as an alternate to API Token
             */
            email?: string;
            /**
             * Secret containing Cloudflare API key/token
             */
            secret?: string;
        }
        /**
         * tunnelSpecCloudflareProvideDefaults sets the appropriate defaults for TunnelSpecCloudflare
         */
        export function tunnelSpecCloudflareProvideDefaults(val: TunnelSpecCloudflare): TunnelSpecCloudflare {
            return {
                ...val,
                CLOUDFLARE_API_KEY: (val.CLOUDFLARE_API_KEY) ?? "CLOUDFLARE_API_KEY",
                CLOUDFLARE_API_TOKEN: (val.CLOUDFLARE_API_TOKEN) ?? "CLOUDFLARE_API_TOKEN",
                CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_FILE) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_FILE",
                CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: (val.CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET) ?? "CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET",
            };
        }

        /**
         * Existing tunnel object. ExistingTunnel and NewTunnel cannot be both empty and are mutually exclusive.
         */
        export interface TunnelSpecExistingTunnel {
            /**
             * Existing Tunnel ID to run on. Tunnel ID and Tunnel Name cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            id?: string;
            /**
             * Existing Tunnel name to run on. Tunnel Name and Tunnel ID cannot be both empty. If both are provided, ID is used if valid, else falls back to Name.
             */
            name?: string;
        }

        /**
         * New tunnel object. NewTunnel and ExistingTunnel cannot be both empty and are mutually exclusive.
         */
        export interface TunnelSpecNewTunnel {
            /**
             * Tunnel name to create on Cloudflare.
             */
            name?: string;
        }

        /**
         * TunnelStatus defines the observed state of Tunnel
         */
        export interface TunnelStatus {
            accountId: string;
            tunnelId: string;
            tunnelName: string;
            zoneId: string;
        }

    }
}
