apiVersion: v1
kind: Service
metadata:
  labels:
    networking.knative.dev/ingress-provider: contour
  name: contour
  namespace: contour-external
spec:
  ports:
  - name: xds
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: contour
  type: ClusterIP
