// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { KustomizationArgs } from "./kustomization";
export type Kustomization = import("./kustomization").Kustomization;
export const Kustomization: typeof import("./kustomization").Kustomization = null as any;
utilities.lazyLoad(exports, ["Kustomization"], () => require("./kustomization"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:kustomize.toolkit.fluxcd.io/v1:Kustomization":
                return new Kustomization(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fluxcd", "kustomize.toolkit.fluxcd.io/v1", _module)
