apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:hpyrz2uIVH5gwqYB08ZAL4v0sjIYa/QDGCYh7U93pX2RoOBUCQ==,iv:kIliK7OalOB/2DvpbRk4oLRUop0dLmq/q571AMqjRL4=,tag:uMyK6qZe/ivy/nOTsp8vwg==,type:str]
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:RNOtj9FTrXDm4ZJJc16Rfjkq5PDL7cHJplTAJY2RHcz24synmVnHK9g2xkySfHEOAOkYTCC+z+nG,iv:fEnRjg5dOJw8/UHuPZXe1pAzoGKY4oTS5AtkrNELosM=,tag:dVWLwhsHJpM9HqBC1sQLig==,type:str]
    PIA_USER: ENC[AES256_GCM,data:GZmbQ4LIEo8=,iv:dg1exq82RXBu78EKagOY3ydmXUtsFbAX7xTfIpdgqSM=,tag:Wo3wwdABXN5WbyVVS47Q0A==,type:str]
    PIA_PASS: ENC[AES256_GCM,data:D+hoGm+rzwaS88xtX1z8Agqg8Q==,iv:6Zt7RoIXzLyVwyEX0dcDp8tkNGPH5ZQoE8vpC3GTaVM=,tag:mOjbAPTD11yVCYzIlGj3oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-14T05:41:18Z"
    mac: ENC[AES256_GCM,data:9bZfqgi3khD/KTMJ/dBQ0y8cgbrdNWYDPuLTymrTwrIYItfE/D5unG1sKuuASUsCMk7dqn3ZSwYrSxVyt7CYCKmHV7V4dqIqB7jjjjqtzLJGYcYpTuAUfo9Wr58j0kqzE230A7fVYmNqjuFlAL6CF2qc3GU4miBlMDHGf1DZt2g=,iv:kmRg1RSydbSbrsYV6Lj8tYSXP8VBf8elZ1kwkgLy0XI=,tag:TB7rusqeRecxa7uf1kiEUw==,type:str]
    pgp:
        - created_at: "2023-02-14T05:41:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ//e3Z8iWc6Oi/nbPYXGA44VJ4aK+433/42sFBXOW9PRnKK
            08K3vIGdjOkH4Hy2P86SnrYS3LA1o61Tyyc8P0is1W4KovtsG7sUsu0C8+DPdVWz
            KaU2z3JkPCvj/0a8qa8H383fyANuJNE8z2Zb0tiyQNxOiteWDv6hiR+aIk5B9vzj
            k3EbL4R3LXBpe+kfmuP4pAO4EAFPM4EJGFD1SdcYKiXxxvEgAdV8s1F1IJXIBLW9
            M/Khx+pQcsQd3EPM1pzrNMhltQ4wfchsIqHqlkoCA/O3YiJKK4TVO9orWwyZe5FE
            dlAst1TDgRdQvEcUehgahYx8ESTvZleaurzY+dBQlIw6Sz5FV4Hpf2KMqDOyGP6z
            MErMqRYT6T0VS6uJBiQXL2q+/5UGOpXryQI9EJr+Z7cHs1lfokZUu9MK+u7VCr5+
            o9ea8ORNc0uMGcBhvZU9/QXQs+yfj9wDhvxFiuJthVk+XkvTlqBFUBDQ8N8ctU/K
            m5puaFOv+fTEaSo5oiw88AOQHo9aurbVUfCfknJJqTtkXrF2iNqevqnrvmYWYBII
            ZqCsqGFP/PKMOAzRurnR1LWlVyNijTcc8izWsvOgBm/H6CPPddqnIAQins0/SGRe
            wgy8OjaZwh9fkQ4vi9mSnEbNawcT/3p/8Ijd5Kwb6H/qcD7sPO1xxMMdPR31TdnU
            ZgEJAhBozVdIW+o53tCy7hB704+dfmnPMYQuWSmPAPbQ8gb3fURKAhyBIYcFMzPC
            aU2L9HpwE6vN16QBv3ZH3JnvtTluBDbQtyqdCLuEIM2m00h1bOZB9EfOUva1TKug
            FaHHy8lMjg==
            =2nzu
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
