apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:qz8lQnztta1ytbbjxzqgd5dQzDaSobZJtIbD00WCnCHyHr65Dg==,iv:RdNIWxsn7rVaCPrHabY11n1NVP4AAylYDsrl6jMxmAU=,tag:PpPRZHXthXXZCURh0Lzofg==,type:str]
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:gIKkkAurmVplaxCxjHKabJKpGQmsJw3uycVsCavkb0FqlEQmo684ffHJF359pu4/9yTlEVdkTFs=,iv:Y62OkczyXl71pE8pJFlv+9cEtmrI2bfHbxlG4Y0P/1E=,tag:lWPTGLGKQ6PeUcTNRyDeYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-13T07:11:03Z"
    mac: ENC[AES256_GCM,data:DrGE9K3oxDKvf2T2IGIc80USXCLPgrhyOpxKZeQf9yJ5uTlul+YnehlWtPSMJJssKhnfhcqaUO+Z5enXA1omVoSqkoTik1BwRiU1lYOOH5PvR8iPF/snjMF7kMZlaINojuXXlQ8aVMunJjC12KA7ArBsUJ+/bKOPQtcxD0K42tM=,iv:eaovd8Vy2qpKrhtPd97IBw50cOLxG55b/aMUKQl37PI=,tag:9kwZ55s4N5aas3pAIC4Oig==,type:str]
    pgp:
        - created_at: "2023-02-13T07:11:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8AQ//WtYj29QUhOEjITDJFfFH5KCAB8ncPa/JKfvN+5t8dzo3
            xrYUxawGLkE/r5Fr+SAXksNKz3AR5DQEKBytWsUBbn8bdXdwCP4c1cxqblWiH7Mv
            B0kSlF5sI03q4fgOUb68stWOQLUrohHmfdWvOIkiXHOu3RRwFaeoi43Q1mCqx+PH
            vISDUvq6lNq2Jnhk7WCdETPMsgioebWVL+K6qC2kDNboTgvMaY2h8AMOqVgt64s3
            KYe7zil1F5IfLMhWrSviYQWXntPIq3pjSj3BeeUViDNI3uMVX5vUWYEmQwei2aqT
            MXnXuq0oy0I1p5bKF80VtsSimsDpe/5LBPJerfQuciIFomdx+MqgBFFQAT1znsyd
            KG33hm25kkCQmdTFE0QhyCSAB8KnA2uP6Og71uDauZqBAjRrKzTudm0KdwdjXsqi
            L5MtQ3k7CZrUDBWX7zonoYLu/n2P3p8QVNCi+FaHxGbL68JL+NaOxnzw082+FRUU
            845B9nA6vZWTRHtCy4vYy39exnRCi6gfNh48sQFgg29F+xVPlSZZJC/hsr3swoxT
            Sp3l3NVKyTKwPSbsfT7Dc2yEkGBDHLMSzf22kDrm2u3rJa6dUpLHO1Rm3lusET9h
            NRWsZzKxvYukIjGXbPo7eqJFxeIuv1It/q2dWLcGLGzh6XWs/zP82cgFLQfmKw3U
            aAEJAhAThxJJL08RL1pY7Ty2WAiIDDCQvD6EY6I2oKuQbAmB4F/IvVap+EYQ8h5r
            oGE5qV6E31iBrnNLXoqEEYAQ9qy4iBG/EUuY5ken0sCjOR1BGGYvPrVAWlQDsNL0
            9a81CADtuDFK
            =+7bG
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
