apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:y1fNTTl53vbe90jevKqS0aV2nIQ3iqEYKQ8Oo6kLwCSB6EhyFw==,iv:7Cbnf2vX7HP60/NUi6skIa+MC+3ynmiHLt5JavKN2dw=,tag:bX1OQYu2niTm1tKKNrNLlQ==,type:str]
    TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:UoJL7vmtSfwFKlpRWwEX+BYnNLlKb0o6E9GW4E87cdGG6oF0vksxTAvOT2+E+lB6u/MAezM0vnKY,iv:E119Ils3IFeSqIvt2BT3hqNg5Vk3IZ9Z87TOCtl7gYA=,tag:lIcw25Fmw3iZfCAaX0mujw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-13T07:18:40Z"
    mac: ENC[AES256_GCM,data:KZ1Otef42rn1adIFeuh2qbh9MRVqXHAwNt20CPvKXhXnZYSZ3+hok8q+voLoxOScx/4syo7Ffegn3t4qgSKTi56o9RIDEni4BSoi7O71iXAFJ2uvSjDZzhI/GugJg7lmGFvfnqEEV4Jy8LcDYDr8zjGUimL0yop1Cp8rTVIveNc=,iv:6aPvs6cmPSh6ce2G3XR7wlQOzyDpaSs9gswN/JZPBB0=,tag:MErssd8OzC5fQAsAQeXnlw==,type:str]
    pgp:
        - created_at: "2023-02-13T07:18:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA76+lw42U5t8ARAAmHMdM2XS2a40o+aI66hV19vurVk+VEnIdG0mFDVxZRgG
            JqyKDQHVePed1pZRZFIv3/6gAqsUzAEOanOIwAj332JW2vUf1f2iJ5qSEmlfvL2W
            zC4ZwdfUkWq21BpOv6rz1bl3FT2q7Gn+dtqf1FXEK9JFBPb33qvFZFBa/0y1XH8/
            frwSPgdFAma0Jxqjhaf3pCSQylxcJHXV5MceWIzAKfqe77Ui3H8MNcAs5eaC3I6u
            SnPzQS5ZVdvDJfFcm1EhEX2h2NaJPhYNRr2GNv2Uc8boKKVgOfqyUTwASChBTX17
            ZPdGMDe06pljlQy4phxK4wNdUw6f2L/bHjOWG7NZRSB/3COZfXra8qwEhK0vJ3GX
            AIvbFIIpT3IQfBscsVZ5vjGo6yw1ekrzsxCIZSB8m8gjdUJh+gq2u9rt1g/+6EHO
            ZI4heZKRzRNqxpZvwFVb1FLlwWJOeI95Ibh9s75ugVVNYB5boM6ZCGBarA0g06j0
            uAplu481GLM5YoXP8k0Idp7JauOAOLwzenDL3YNt7+8UtkrZD7NJREunH17+KC/7
            md7u07Nf1FaOAE18Hrdoszi8BqghYcAvtvU5ZXv3EviVhLCxHMUWJd7ZmYm0y4P3
            TLnveBmMlR4oXY84lFRjKciftHjLfO5EmfXsxLLsqgkbUwNm1XQG8r/T8iAArNDU
            aAEJAhCQdoV2yl1Ebl1I6bBEtayV0RvlE331UnlXXvG02nxqCxaKWMnV5sBipM8p
            6RQA4TtK47qTdoBqrHWWerkNodE9svXJ8Nb8dGGA04HdypN7z9hBKSSGi32y/o0h
            4BScBvtoBg2S
            =EO8l
            -----END PGP MESSAGE-----
          fp: 40426439B25D67BD53C70F42D9C267B8CD0937BF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
