apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  labels:
    app: atuin
  name: atuin
  namespace: atuin
subjects:
- name: atuin
tunnelRef:
  kind: ClusterTunnel
  name: xnauts-net-tunnel
