// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Alert is the Schema for the alerts API
 */
export class Alert extends pulumi.CustomResource {
    /**
     * Get an existing Alert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Alert {
        return new Alert(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:notification.toolkit.fluxcd.io/v1beta2:Alert';

    /**
     * Returns true if the given object is an instance of Alert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Alert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Alert.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"notification.toolkit.fluxcd.io/v1beta2" | undefined>;
    public readonly kind!: pulumi.Output<"Alert" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * AlertSpec defines an alerting rule for events involving a list of objects.
     */
    public readonly spec!: pulumi.Output<outputs.notification.v1beta2.AlertSpec | undefined>;
    /**
     * AlertStatus defines the observed state of the Alert.
     */
    public readonly status!: pulumi.Output<outputs.notification.v1beta2.AlertStatus | undefined>;

    /**
     * Create a Alert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AlertArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "notification.toolkit.fluxcd.io/v1beta2";
            resourceInputs["kind"] = "Alert";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.notification.v1beta2.alertSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Alert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Alert resource.
 */
export interface AlertArgs {
    apiVersion?: pulumi.Input<"notification.toolkit.fluxcd.io/v1beta2">;
    kind?: pulumi.Input<"Alert">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * AlertSpec defines an alerting rule for events involving a list of objects.
     */
    spec?: pulumi.Input<inputs.notification.v1beta2.AlertSpecArgs>;
    /**
     * AlertStatus defines the observed state of the Alert.
     */
    status?: pulumi.Input<inputs.notification.v1beta2.AlertStatusArgs>;
}
