apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: onepassword-connect-helm-c8fa9387
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-1.16.0
  name: onepassword-connect-helm-c8fa9387-health-check
  namespace: media
spec:
  containers:
    - command:
        - curl
        - http://onepassword-connect:8080/health
      image: curlimages/curl
      name: curl
  restartPolicy: Never
