apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: onepassword-connect-helm-c8fa9387
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-1.16.0
  name: onepassword-connect
  namespace: onepassword
spec:
  ports:
    - name: connect-sync
      port: 8081
    - name: connect-api
      port: 8080
  selector:
    app: onepassword-connect
  type: ClusterIP
