apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: onepassword-connect-helm-c8fa9387
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.3
    helm.sh/chart: connect-1.16.0
  name: onepassword-connect-operator
  namespace: onepassword
