// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * HTTPProxy is an Ingress CRD specification.
 */
export class HTTPProxy extends pulumi.CustomResource {
    /**
     * Get an existing HTTPProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): HTTPProxy {
        return new HTTPProxy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:projectcontour.io/v1:HTTPProxy';

    /**
     * Returns true if the given object is an instance of HTTPProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is HTTPProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === HTTPProxy.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"projectcontour.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"HTTPProxy" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * HTTPProxySpec defines the spec of the CRD.
     */
    public readonly spec!: pulumi.Output<outputs.projectcontour.v1.HTTPProxySpec>;
    /**
     * Status is a container for computed information about the HTTPProxy.
     */
    public readonly status!: pulumi.Output<outputs.projectcontour.v1.HTTPProxyStatus | undefined>;

    /**
     * Create a HTTPProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: HTTPProxyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "projectcontour.io/v1";
            resourceInputs["kind"] = "HTTPProxy";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.projectcontour.v1.httpproxySpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(HTTPProxy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a HTTPProxy resource.
 */
export interface HTTPProxyArgs {
    apiVersion?: pulumi.Input<"projectcontour.io/v1">;
    kind?: pulumi.Input<"HTTPProxy">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * HTTPProxySpec defines the spec of the CRD.
     */
    spec?: pulumi.Input<inputs.projectcontour.v1.HTTPProxySpecArgs>;
    /**
     * Status is a container for computed information about the HTTPProxy.
     */
    status?: pulumi.Input<inputs.projectcontour.v1.HTTPProxyStatusArgs>;
}
