// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { HTTPProxyArgs } from "./httpproxy";
export type HTTPProxy = import("./httpproxy").HTTPProxy;
export const HTTPProxy: typeof import("./httpproxy").HTTPProxy = null as any;
utilities.lazyLoad(exports, ["HTTPProxy"], () => require("./httpproxy"));

export { TLSCertificateDelegationArgs } from "./tlscertificateDelegation";
export type TLSCertificateDelegation = import("./tlscertificateDelegation").TLSCertificateDelegation;
export const TLSCertificateDelegation: typeof import("./tlscertificateDelegation").TLSCertificateDelegation = null as any;
utilities.lazyLoad(exports, ["TLSCertificateDelegation"], () => require("./tlscertificateDelegation"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:projectcontour.io/v1:HTTPProxy":
                return new HTTPProxy(name, <any>undefined, { urn })
            case "kubernetes:projectcontour.io/v1:TLSCertificateDelegation":
                return new TLSCertificateDelegation(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("projectcontour", "projectcontour.io/v1", _module)
