// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * TLSCertificateDelegation is an TLS Certificate Delegation CRD specification. See design/tls-certificate-delegation.md for details.
 */
export class TLSCertificateDelegation extends pulumi.CustomResource {
    /**
     * Get an existing TLSCertificateDelegation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TLSCertificateDelegation {
        return new TLSCertificateDelegation(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:projectcontour.io/v1:TLSCertificateDelegation';

    /**
     * Returns true if the given object is an instance of TLSCertificateDelegation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TLSCertificateDelegation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TLSCertificateDelegation.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"projectcontour.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"TLSCertificateDelegation" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * TLSCertificateDelegationSpec defines the spec of the CRD
     */
    public readonly spec!: pulumi.Output<outputs.projectcontour.v1.TLSCertificateDelegationSpec>;
    /**
     * TLSCertificateDelegationStatus allows for the status of the delegation to be presented to the user.
     */
    public readonly status!: pulumi.Output<outputs.projectcontour.v1.TLSCertificateDelegationStatus | undefined>;

    /**
     * Create a TLSCertificateDelegation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TLSCertificateDelegationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "projectcontour.io/v1";
            resourceInputs["kind"] = "TLSCertificateDelegation";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TLSCertificateDelegation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TLSCertificateDelegation resource.
 */
export interface TLSCertificateDelegationArgs {
    apiVersion?: pulumi.Input<"projectcontour.io/v1">;
    kind?: pulumi.Input<"TLSCertificateDelegation">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * TLSCertificateDelegationSpec defines the spec of the CRD
     */
    spec?: pulumi.Input<inputs.projectcontour.v1.TLSCertificateDelegationSpecArgs>;
    /**
     * TLSCertificateDelegationStatus allows for the status of the delegation to be presented to the user.
     */
    status?: pulumi.Input<inputs.projectcontour.v1.TLSCertificateDelegationStatusArgs>;
}
