// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Kustomization is the Schema for the kustomizations API.
 */
export class Kustomization extends pulumi.CustomResource {
    /**
     * Get an existing Kustomization resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Kustomization {
        return new Kustomization(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:kustomize.toolkit.fluxcd.io/v1beta2:Kustomization';

    /**
     * Returns true if the given object is an instance of Kustomization.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Kustomization {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Kustomization.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"kustomize.toolkit.fluxcd.io/v1beta2" | undefined>;
    public readonly kind!: pulumi.Output<"Kustomization" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * KustomizationSpec defines the configuration to calculate the desired state from a Source using Kustomize.
     */
    public readonly spec!: pulumi.Output<outputs.kustomize.v1beta2.KustomizationSpec | undefined>;
    /**
     * KustomizationStatus defines the observed state of a kustomization.
     */
    public readonly status!: pulumi.Output<outputs.kustomize.v1beta2.KustomizationStatus | undefined>;

    /**
     * Create a Kustomization resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KustomizationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "kustomize.toolkit.fluxcd.io/v1beta2";
            resourceInputs["kind"] = "Kustomization";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.kustomize.v1beta2.kustomizationSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Kustomization.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Kustomization resource.
 */
export interface KustomizationArgs {
    apiVersion?: pulumi.Input<"kustomize.toolkit.fluxcd.io/v1beta2">;
    kind?: pulumi.Input<"Kustomization">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * KustomizationSpec defines the configuration to calculate the desired state from a Source using Kustomize.
     */
    spec?: pulumi.Input<inputs.kustomize.v1beta2.KustomizationSpecArgs>;
    /**
     * KustomizationStatus defines the observed state of a kustomization.
     */
    status?: pulumi.Input<inputs.kustomize.v1beta2.KustomizationStatusArgs>;
}
