apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    matchLabels:
      workload: radarr
  template:
    metadata:
      labels:
        workload: radarr
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/pbar1/radarr:latest
          imagePullPolicy: Always
          name: radarr
          ports:
            - containerPort: 7878
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 100
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            - mountPath: /movies
              name: movies
      volumes:
        - emptyDir:
            medium: ""
          name: tmp
        - hostPath:
            path: /zssd/general/config/radarr
          name: config
        - hostPath:
            path: /data/torrents
          name: downloads
        - hostPath:
            path: /data/media/movies
          name: movies
