apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    matchLabels:
      workload: sonarr
  template:
    metadata:
      labels:
        workload: sonarr
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Los_Angeles
          image: ghcr.io/pbar1/sonarr:latest
          imagePullPolicy: Always
          name: sonarr
          ports:
            - containerPort: 8989
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 100
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            - mountPath: /tv
              name: tv
      volumes:
        - emptyDir:
            medium: ""
          name: tmp
        - hostPath:
            path: /zssd/general/config/sonarr
          name: config
        - hostPath:
            path: /data/torrents
          name: downloads
        - hostPath:
            path: /data/media/tv
          name: tv
