// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { AlertArgs } from "./alert";
export type Alert = import("./alert").Alert;
export const Alert: typeof import("./alert").Alert = null as any;
utilities.lazyLoad(exports, ["Alert"], () => require("./alert"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ReceiverArgs } from "./receiver";
export type Receiver = import("./receiver").Receiver;
export const Receiver: typeof import("./receiver").Receiver = null as any;
utilities.lazyLoad(exports, ["Receiver"], () => require("./receiver"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:notification.toolkit.fluxcd.io/v1beta1:Alert":
                return new Alert(name, <any>undefined, { urn })
            case "kubernetes:notification.toolkit.fluxcd.io/v1beta1:Provider":
                return new Provider(name, <any>undefined, { urn })
            case "kubernetes:notification.toolkit.fluxcd.io/v1beta1:Receiver":
                return new Receiver(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fluxcd", "notification.toolkit.fluxcd.io/v1beta1", _module)
