// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Provider is the Schema for the providers API
 */
export class Provider extends pulumi.CustomResource {
    /**
     * Get an existing Provider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Provider {
        return new Provider(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:notification.toolkit.fluxcd.io/v1beta1:Provider';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"notification.toolkit.fluxcd.io/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"Provider" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ProviderSpec defines the desired state of Provider
     */
    public readonly spec!: pulumi.Output<outputs.notification.v1beta1.ProviderSpec | undefined>;
    /**
     * ProviderStatus defines the observed state of Provider
     */
    public readonly status!: pulumi.Output<outputs.notification.v1beta1.ProviderStatus | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "notification.toolkit.fluxcd.io/v1beta1";
            resourceInputs["kind"] = "Provider";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    apiVersion?: pulumi.Input<"notification.toolkit.fluxcd.io/v1beta1">;
    kind?: pulumi.Input<"Provider">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ProviderSpec defines the desired state of Provider
     */
    spec?: pulumi.Input<inputs.notification.v1beta1.ProviderSpecArgs>;
    /**
     * ProviderStatus defines the observed state of Provider
     */
    status?: pulumi.Input<inputs.notification.v1beta1.ProviderStatusArgs>;
}
