apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
    - --dns01-recursive-nameservers-only
    installCRDs: false
    podAnnotations:
      operator.1password.io/item-name: cloudflare-creds
      operator.1password.io/item-path: vaults/pbcloud/items/cloudflare
    podDnsConfig:
      nameservers:
      - 1.1.1.1
      - 9.9.9.9
    podDnsPolicy: None
    replicaCount: 1
    webhook:
      enabled: true
