apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: xnauts-net-tls
  namespace: cert-manager
spec:
  delegations:
  - secretName: xnauts-net-tls
    targetNamespaces:
    - '*'
