apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-relay
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
  values:
    config:
      authKey: "${TAILSCALE_AUTH_KEY}"
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "${NETWORK_CIDR}"
        TAILSCALE_HOSTNAME: tec
