apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: monitoring
spec:
  force: false
  interval: 24h
  path: ./materialized/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
