// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ContourConfiguration is the schema for a Contour instance.
 */
export class ContourConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing ContourConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ContourConfiguration {
        return new ContourConfiguration(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:projectcontour.io/v1alpha1:ContourConfiguration';

    /**
     * Returns true if the given object is an instance of ContourConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContourConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContourConfiguration.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"projectcontour.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"ContourConfiguration" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ContourConfigurationSpec represents a configuration of a Contour controller. It contains most of all the options that can be customized, the other remaining options being command line flags.
     */
    public readonly spec!: pulumi.Output<outputs.projectcontour.v1alpha1.ContourConfigurationSpec>;
    /**
     * ContourConfigurationStatus defines the observed state of a ContourConfiguration resource.
     */
    public readonly status!: pulumi.Output<outputs.projectcontour.v1alpha1.ContourConfigurationStatus | undefined>;

    /**
     * Create a ContourConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ContourConfigurationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "projectcontour.io/v1alpha1";
            resourceInputs["kind"] = "ContourConfiguration";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.projectcontour.v1alpha1.contourConfigurationSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContourConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ContourConfiguration resource.
 */
export interface ContourConfigurationArgs {
    apiVersion?: pulumi.Input<"projectcontour.io/v1alpha1">;
    kind?: pulumi.Input<"ContourConfiguration">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ContourConfigurationSpec represents a configuration of a Contour controller. It contains most of all the options that can be customized, the other remaining options being command line flags.
     */
    spec?: pulumi.Input<inputs.projectcontour.v1alpha1.ContourConfigurationSpecArgs>;
    /**
     * ContourConfigurationStatus defines the observed state of a ContourConfiguration resource.
     */
    status?: pulumi.Input<inputs.projectcontour.v1alpha1.ContourConfigurationStatusArgs>;
}
