// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ExtensionService is the schema for the Contour extension services API. An ExtensionService resource binds a network service to the Contour API so that Contour API features can be implemented by collaborating components.
 */
export class ExtensionService extends pulumi.CustomResource {
    /**
     * Get an existing ExtensionService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ExtensionService {
        return new ExtensionService(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:projectcontour.io/v1alpha1:ExtensionService';

    /**
     * Returns true if the given object is an instance of ExtensionService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ExtensionService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ExtensionService.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"projectcontour.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"ExtensionService" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ExtensionServiceSpec defines the desired state of an ExtensionService resource.
     */
    public readonly spec!: pulumi.Output<outputs.projectcontour.v1alpha1.ExtensionServiceSpec | undefined>;
    /**
     * ExtensionServiceStatus defines the observed state of an ExtensionService resource.
     */
    public readonly status!: pulumi.Output<outputs.projectcontour.v1alpha1.ExtensionServiceStatus | undefined>;

    /**
     * Create a ExtensionService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ExtensionServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "projectcontour.io/v1alpha1";
            resourceInputs["kind"] = "ExtensionService";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ExtensionService.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ExtensionService resource.
 */
export interface ExtensionServiceArgs {
    apiVersion?: pulumi.Input<"projectcontour.io/v1alpha1">;
    kind?: pulumi.Input<"ExtensionService">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ExtensionServiceSpec defines the desired state of an ExtensionService resource.
     */
    spec?: pulumi.Input<inputs.projectcontour.v1alpha1.ExtensionServiceSpecArgs>;
    /**
     * ExtensionServiceStatus defines the observed state of an ExtensionService resource.
     */
    status?: pulumi.Input<inputs.projectcontour.v1alpha1.ExtensionServiceStatusArgs>;
}
