// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ContourConfigurationArgs } from "./contourConfiguration";
export type ContourConfiguration = import("./contourConfiguration").ContourConfiguration;
export const ContourConfiguration: typeof import("./contourConfiguration").ContourConfiguration = null as any;
utilities.lazyLoad(exports, ["ContourConfiguration"], () => require("./contourConfiguration"));

export { ContourDeploymentArgs } from "./contourDeployment";
export type ContourDeployment = import("./contourDeployment").ContourDeployment;
export const ContourDeployment: typeof import("./contourDeployment").ContourDeployment = null as any;
utilities.lazyLoad(exports, ["ContourDeployment"], () => require("./contourDeployment"));

export { ExtensionServiceArgs } from "./extensionService";
export type ExtensionService = import("./extensionService").ExtensionService;
export const ExtensionService: typeof import("./extensionService").ExtensionService = null as any;
utilities.lazyLoad(exports, ["ExtensionService"], () => require("./extensionService"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:projectcontour.io/v1alpha1:ContourConfiguration":
                return new ContourConfiguration(name, <any>undefined, { urn })
            case "kubernetes:projectcontour.io/v1alpha1:ContourDeployment":
                return new ContourDeployment(name, <any>undefined, { urn })
            case "kubernetes:projectcontour.io/v1alpha1:ExtensionService":
                return new ExtensionService(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("projectcontour", "projectcontour.io/v1alpha1", _module)
