apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: xnauts-net-tunnel
spec:
  cloudflare:
    CLOUDFLARE_API_KEY: CLOUDFLARE_API_KEY
    CLOUDFLARE_API_TOKEN: CLOUDFLARE_API_TOKEN
    CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: CLOUDFLARE_TUNNEL_CREDENTIAL_FILE
    CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET
    accountId: 17d824c0799bab4158f3b78200dc4322
    domain: xnauts.net
    email: piercebartine@gmail.com
    secret: cloudflare-operator-creds
  fallbackTarget: http_status:404
  image: cloudflare/cloudflared:2022.12.1
  newTunnel:
    name: xnauts-net-tunnel
  noTlsVerify: false
  size: 1
