apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: cloudflare-operator-controller-manager-metrics-service
  namespace: cloudflare-operator-system
spec:
  clusterIP: 10.43.58.110
  clusterIPs:
  - 10.43.58.110
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
