apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisparr
  namespace: download
spec:
  interval: 24h
  chart:
    spec:
      chart: whisparr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: false
