#!/usr/bin/env bash

set -euo pipefail

kubectl create secret generic \
    gluetun \
    --namespace="media" \
    --from-literal="WIREGUARD_PRIVATE_KEY=$(op item get 'gluetun' --fields WIREGUARD_PRIVATE_KEY --reveal)" \
    --from-literal="WIREGUARD_PRESHARED_KEY=$(op item get 'gluetun' --fields WIREGUARD_PRESHARED_KEY --reveal)" \
    --dry-run=client \
    --output=yaml |
    kubectl apply -f -
