apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.3.1
    chart: kube-prometheus-stack-65.3.1
    heritage: Helm
    release: monitoring-kube-prometheus-stack-helm-c8a1ee83
  name: monitoring-kube-prometheus
  namespace: monitoring
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  automountServiceAccountToken: true
  externalUrl: http://monitoring-kube-prometheus-alertmanager.monitoring:9093
  image: quay.io/prometheus/alertmanager:v0.27.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: monitoring-kube-prometheus-alertmanager
  version: v0.27.0
