apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.3.1
    chart: kube-prometheus-stack-65.3.1
    heritage: Helm
    release: monitoring-kube-prometheus-stack-helm-c8a1ee83
  name: monitoring-kube-prometheus-operator
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-kube-prometheus-operator
subjects:
  - kind: ServiceAccount
    name: monitoring-kube-prometheus-operator
    namespace: monitoring
