apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2
    helm.sh/chart: grafana-8.5.5
  name: monitoring-kube-prometheus-stack-helm-c8a1ee83-grafana-test
  namespace: monitoring
spec:
  containers:
    - command:
        - /opt/bats/bin/bats
        - -t
        - /tests/run.sh
      image: docker.io/bats/bats:v1.4.1
      imagePullPolicy: IfNotPresent
      name: monitoring-kube-prometheus-stack-helm-c8a1ee83-test
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  restartPolicy: Never
  serviceAccountName: monitoring-kube-prometheus-stack-helm-c8a1ee83-grafana-test
  volumes:
    - configMap:
        name: monitoring-kube-prometheus-stack-helm-c8a1ee83-grafana-test
      name: tests
