apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-alertmanager
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.3.1
    chart: kube-prometheus-stack-65.3.1
    heritage: Helm
    release: monitoring-kube-prometheus-stack-helm-c8a1ee83
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
automountServiceAccountToken: true
