apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.8.2
    helm.sh/chart: prometheus-node-exporter-4.39.0
    jobLabel: node-exporter
    release: monitoring-kube-prometheus-stack-helm-c8a1ee83
  name: monitoring-kube-prometheus-stack-helm-c8a1ee83-prometheus-node
  namespace: monitoring
spec:
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/name: prometheus-node-exporter
  type: ClusterIP
