apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: monitoring-kube-prometheus-stack-helm-c8a1ee83
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.3.1
    chart: kube-prometheus-stack-65.3.1
    heritage: Helm
    release: monitoring-kube-prometheus-stack-helm-c8a1ee83
    self-monitor: "true"
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
    - appProtocol: http
      name: reloader-web
      port: 8080
      targetPort: reloader-web
  selector:
    alertmanager: monitoring-kube-prometheus
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
