apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: amd-gpu
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: flux-system
  values:
    labeller:
      enabled: true

    dp:
      image:
        # https://github.com/RadeonOpenCompute/k8s-device-plugin/issues/31#issuecomment-1361061842
        tag: "1.18.0"
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          group: rbac.authorization.k8s.io
          version: v1beta1
          name: .*
        patch:
        - op: replace
          path: /apiVersion
          value: rbac.authorization.k8s.io/v1
