apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.22.3
    helm.sh/chart: gitea-10.5.0
    version: 1.22.3
  name: gitea-test-connection
  namespace: cicd
spec:
  containers:
    - args:
        - gitea-http:3000
      command:
        - wget
      image: busybox:latest
      name: wget
  restartPolicy: Never
