apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  chart:
    spec:
      chart: contour
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    envoy:
      service:
        ipFamilyPolicy: RequireDualStack
      useHostPort: false
