// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { GitRepositoryArgs } from "./gitRepository";
export type GitRepository = import("./gitRepository").GitRepository;
export const GitRepository: typeof import("./gitRepository").GitRepository = null as any;
utilities.lazyLoad(exports, ["GitRepository"], () => require("./gitRepository"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:source.toolkit.fluxcd.io/v1:GitRepository":
                return new GitRepository(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fluxcd", "source.toolkit.fluxcd.io/v1", _module)
