apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "kube-prometheus-stack"
  namespace: "monitoring"
spec:
  chart:
    spec:
      chart: "kube-prometheus-stack"
      sourceRef:
        kind: "HelmRepository"
        name: "prometheus-community"
        namespace: "flux-system"
  interval: "24h"
  values:
    alertmanager:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        enabled: true
        hosts:
        - host: "alertmanager.${DOMAIN}"
          paths:
          - path: "/"
            pathType: "Prefix"
        tls:
        - hosts:
          - "alertmanager.${DOMAIN}"
          secretName: "alertmanager.${DOMAIN}-tls"