// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import {ObjectMeta} from "../meta/v1";

export namespace onepassword {
    export namespace v1 {
        /**
         * OnePasswordItemSpec defines the desired state of OnePasswordItem
         */
        export interface OnePasswordItemSpec {
            itemPath?: string;
        }

        /**
         * OnePasswordItemStatus defines the observed state of OnePasswordItem
         */
        export interface OnePasswordItemStatus {
            conditions: outputs.onepassword.v1.OnePasswordItemStatusConditions[];
        }

        export interface OnePasswordItemStatusConditions {
            /**
             * Last time the condition transit from one status to another.
             */
            lastTransitionTime?: string;
            /**
             * Human-readable message indicating details about last transition.
             */
            message?: string;
            /**
             * Status of the condition, one of True, False, Unknown.
             */
            status: string;
            /**
             * Type of job condition, Completed.
             */
            type: string;
        }

    }
}
