apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
      version: '*'
  interval: 24h
  values:
    env:
      PGID: 100
      PUID: 1000
      TZ: America/Los_Angeles
    image:
      imagePullPolicy: Always
      repository: ghcr.io/home-assistant/home-assistant
      tag: latest
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        hosts:
        - host: home-assistant.xnauts.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - home-assistant.xnauts.net
          secretName: home-assistant-tls
    persistence:
      config:
        enabled: true
        hostPath: /data/general/config/home-assistant
        mountPath: /config
        type: hostPath
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/home-assistant: unconfined
    podSecurityContext:
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      capabilities:
        add:
        - NET_RAW
