// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ReceiverArgs } from "./receiver";
export type Receiver = import("./receiver").Receiver;
export const Receiver: typeof import("./receiver").Receiver = null as any;
utilities.lazyLoad(exports, ["Receiver"], () => require("./receiver"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:notification.toolkit.fluxcd.io/v1:Receiver":
                return new Receiver(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fluxcd", "notification.toolkit.fluxcd.io/v1", _module)
