// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Receiver is the Schema for the receivers API.
 */
export class Receiver extends pulumi.CustomResource {
    /**
     * Get an existing Receiver resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Receiver {
        return new Receiver(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:notification.toolkit.fluxcd.io/v1:Receiver';

    /**
     * Returns true if the given object is an instance of Receiver.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Receiver {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Receiver.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"notification.toolkit.fluxcd.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"Receiver" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ReceiverSpec defines the desired state of the Receiver.
     */
    public readonly spec!: pulumi.Output<outputs.notification.v1.ReceiverSpec | undefined>;
    /**
     * ReceiverStatus defines the observed state of the Receiver.
     */
    public readonly status!: pulumi.Output<outputs.notification.v1.ReceiverStatus | undefined>;

    /**
     * Create a Receiver resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ReceiverArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "notification.toolkit.fluxcd.io/v1";
            resourceInputs["kind"] = "Receiver";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.notification.v1.receiverSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Receiver.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Receiver resource.
 */
export interface ReceiverArgs {
    apiVersion?: pulumi.Input<"notification.toolkit.fluxcd.io/v1">;
    kind?: pulumi.Input<"Receiver">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ReceiverSpec defines the desired state of the Receiver.
     */
    spec?: pulumi.Input<inputs.notification.v1.ReceiverSpecArgs>;
    /**
     * ReceiverStatus defines the observed state of the Receiver.
     */
    status?: pulumi.Input<inputs.notification.v1.ReceiverStatusArgs>;
}
